// -*- mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
// vi: set et ts=4 sw=4 sts=4:
//
// SPDX-FileCopyrightInfo: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
// SPDX-License-Identifier: GPL-3.0-or-later
//
#ifndef BENCHMARKS_VOIDS_PROBLEM_HH
#define BENCHMARKS_VOIDS_PROBLEM_HH

#include <dumux/common/math.hh>
#include <dumux/common/boundarytypes.hh>
#include <dumux/common/parameters.hh>
#include <dumux/common/properties.hh>

#include <dumux/io/vtkoutputmodule.hh>

#include <dumux/porousmediumflow/problem.hh>

#include "exchangefluxcalculator.hh"

#include <iomanip>

namespace Dumux {

template <class TypeTag>
class VoidsProblem : public PorousMediumFlowProblem<TypeTag>
{
    using ParentType = PorousMediumFlowProblem<TypeTag>;
    using Scalar = GetPropType<TypeTag, Properties::Scalar>;
    using PointSource = GetPropType<TypeTag, Properties::PointSource>;
    using PrimaryVariables = GetPropType<TypeTag, Properties::PrimaryVariables>;
    using BoundaryTypes = Dumux::BoundaryTypes<GetPropType<TypeTag, Properties::ModelTraits>::numEq()>;
    using GridGeometry = GetPropType<TypeTag, Properties::GridGeometry>;
    using GridView = typename GridGeometry::GridView;
    using FVElementGeometry = typename GridGeometry::LocalView;
    using SubControlVolume = typename GridGeometry::SubControlVolume;
    using SubControlVolumeFace = typename GridGeometry::SubControlVolumeFace;
    using SolutionVector = GetPropType<TypeTag, Properties::SolutionVector>;
    using GridVariables = GetPropType<TypeTag, Properties::GridVariables>;
    using Element = typename GridView::template Codim<0>::Entity;
    using GlobalPosition = typename GridGeometry::GlobalCoordinate;
    using NumEqVector = Dumux::NumEqVector<PrimaryVariables>;
    using FluidSystem = GetPropType<TypeTag, Properties::FluidSystem>;
    using DimWorldVector = Dune::FieldVector<Scalar, GridView::dimensionworld>;

    using CouplingManager = GetPropType<TypeTag, Properties::CouplingManager>;


    // copy some indices for convenience
    using Indices = typename GetPropType<TypeTag, Properties::ModelTraits>::Indices;
    enum {
        // indices of the primary variables
        pressureIdx = Indices::pressureIdx,
        temperatureIdx = Indices::temperatureIdx
    };
    enum {
        // index of the transport equation
        conti0EqIdx = Indices::conti0EqIdx,
        energyEqIdx = Indices::energyEqIdx
    };

public:
    template<class SpatialParams>
    VoidsProblem(std::shared_ptr<const GridGeometry> gridGeometry,
                std::shared_ptr<SpatialParams> spatialParams,
                std::shared_ptr<CouplingManager> couplingManager,
                std::shared_ptr<ExchangeFluxCalculator<TypeTag>> exchangeFluxCalculator)
    : ParentType(gridGeometry, spatialParams, "Voids")
    , couplingManager_(couplingManager)
    , exchangeFluxCalculator_(exchangeFluxCalculator)

    {
        //read parameters from input file
        name_  =  getParam<std::string>("Vtk.OutputName") + "_" + getParamFromGroup<std::string>(this->paramGroup(), "Problem.Name");
        injectionRate_ = getParamFromGroup<Scalar>(this->paramGroup(), "Problem.InjectionRate");
        injectionTemperature_ = getParamFromGroup<Scalar>(this->paramGroup(), "Problem.InjectionTemperature");
        nusseltNumbers_.resize(this->gridGeometry().gridView().size(0));
        energySources_.resize(gridGeometry->numDofs());
    }


    /*!
     * \name Problem parameters
     */
    // \{

    /*!
     * \brief The problem name.
     *
     * This is used as a prefix for files generated by the simulation.
     */
    const std::string& name() const
    { return name_; }

    // \}
    /*!
     * \name Boundary conditions
     */
    // \{

   /*!
     * \brief Specifies which kind of boundary condition should be
     *        used for which equation on a given boundary segment.
     *
     * \param globalPos The global position
     */
    BoundaryTypes boundaryTypesAtPos(const GlobalPosition &globalPos) const
    {
        BoundaryTypes values;
        values.setAllNeumann();
        if(globalPos[0] > this->gridGeometry().bBoxMax()[0] - eps_)
            values.setDirichlet(pressureIdx);
        return values;
    }

    /*!
     * \brief Evaluates the boundary conditions for a Dirichlet control volume.
     *
     * \param globalPos The global position
     *
     * For this method, the \a values parameter stores primary variables.
     */
    PrimaryVariables dirichletAtPos(const GlobalPosition& globalPos) const
    {
        PrimaryVariables values(initialAtPos(globalPos));
        return values;
    }

    /*!
     * \brief Evaluate the boundary conditions for a neumann
     *        boundary segment.
     *
     * This is the method for the case where the Neumann condition is
     * potentially solution dependent
     *
     * \param element The finite element
     * \param fvGeometry The finite-volume geometry
     * \param elemVolVars All volume variables for the element
     * \param elemFluxVarsCache Flux variables caches for all faces in stencil
     * \param scvf The sub control volume face
     *
     * Negative values mean influx.
     * E.g. for the mass balance that would be the mass flux in \f$ [ kg / (m^2 \cdot s)] \f$.
     */
    template<class ElementVolumeVariables, class ElementFluxVariablesCache>
    NumEqVector neumann(const Element& element,
                        const FVElementGeometry& fvGeometry,
                        const ElementVolumeVariables& elemVolVars,
                        const ElementFluxVariablesCache& elemFluxVarsCache,
                        const SubControlVolumeFace& scvf) const
    {
        const GlobalPosition globalPos = scvf.ipGlobal();
        const auto& insideVolVars = elemVolVars[scvf.insideScvIdx()];

        const auto eIdx = this->gridGeometry().elementMapper().index(element);
        const auto area = M_PI * pow(this->spatialParams().innerRadius(eIdx), 2);

        // initialize values to zero, i.e. no-flow Neumann boundary conditions
        NumEqVector values(0.0);

        // get the inflow from params.input
        if(globalPos[0] < this->gridGeometry().bBoxMin()[0] + eps_)
        {
            // injectionRate_ [m³/s] converted to mass flux per area [kg/(m² s)]
            values[conti0EqIdx] = -injectionRate_ * insideVolVars.density() / area;
            values[energyEqIdx] = values[conti0EqIdx] * FluidSystem::enthalpy(injectionTemperature_, insideVolVars.pressure());
        }

        // get the mass flux from the pressure gradient and set the energy flux accordingly
        else
        {
            // calculate mass flux over the boundary. This works only for outflow
            static const bool enableGravity = getParamFromGroup<bool>(this->paramGroup(), "Problem.EnableGravity");
            const auto& fluxVarsCache = elemFluxVarsCache[scvf];

            auto K = insideVolVars.permeability();

            // evaluate gradP - rho*g at integration point
            DimWorldVector gradP(0.0);
            const Scalar rho = insideVolVars.density();
            for (auto&& scv : scvs(fvGeometry))
            {
                const auto& volVars = elemVolVars[scv];

                // the global shape function gradient
                gradP.axpy(volVars.pressure(), fluxVarsCache.gradN(scv.indexInElement()));
            }

            if (enableGravity)
                gradP.axpy(-rho, this->spatialParams().gravity(scvf.center()));

            // apply the permeability and return the velocity
            const Scalar velocity = -1.0*vtmv(scvf.unitOuterNormal(), K, gradP) / insideVolVars.viscosity();

            values[energyEqIdx] = velocity * rho * insideVolVars.enthalpy(/*phaseIndex*/0);
        }

        return values;
    }


    // \}

    /*!
     * \name Volume terms
     */
    // \{

     /*!
     * \brief Applies a vector of point sources which are possibly solution dependent.
     *
     * \param pointSources A vector of PointSource s that contain
              source values for all phases and space positions.
     *
     * For this method, the \a values method of the point source
     * has to return the absolute mass rate in kg/s. Positive values mean
     * that mass is created, negative ones mean that it vanishes.
     */
    void addPointSources(std::vector<PointSource>& pointSources) const
    { pointSources = this->couplingManager().lowDimPointSources(); }

    /*!
     * \brief Evaluates the point sources (added by addPointSources)
     *        for all phases within a given sub-control-volume.
     *
     * This is the method for the case where the point source is
     * solution dependent and requires some quantities that
     * are specific to the fully-implicit method.
     *
     * \param source A single point source
     * \param element The finite element
     * \param fvGeometry The finite-volume geometry
     * \param elemVolVars All volume variables for the element
     * \param scv The sub-control volume within the element
     *
     * For this method, the \a values() method of the point sources returns
     * the absolute rate mass generated or annihilated in kg/s. Positive values mean
     * that mass is created, negative ones mean that it vanishes.
     */
    template<class ElementVolumeVariables>
    void pointSource(PointSource& source,
                     const Element &element,
                     const FVElementGeometry& fvGeometry,
                     const ElementVolumeVariables& elemVolVars,
                     const SubControlVolume &scv) const
    {
        NumEqVector sourceValue = -exchangeFluxCalculator_->computeSourceValues(source.id()); //negative values because positive flux in exchangefluxcalculator is defined from 1D to 3D

        if constexpr(CouplingManager::couplingMode == Embedded1d3dCouplingMode::kernel)
        {
            sourceValue[conti0EqIdx] *= exchangeFluxCalculator_->massFluxScalingFactor(source.id());
            sourceValue[energyEqIdx] *= exchangeFluxCalculator_->energyFluxScalingFactor(source.id());
        }

        source  = sourceValue*source.quadratureWeight()*source.integrationElement();
    }

    /*!
     * \brief Evaluates the initial value for a control volume.
     *
     * For this method, the \a priVars parameter stores primary
     * variables.
     */
    PrimaryVariables initialAtPos(const GlobalPosition &globalPos) const
    {
        PrimaryVariables values;
        values[temperatureIdx] = 273.15 + 20.0;
        values[pressureIdx] = 1.0e5 ;
        return values;
    }

    // \}

    //! Called after every time step
    //! Output the total global exchange term
    void computeSourceIntegral(const SolutionVector& sol, const GridVariables& gridVars)
    {
        PrimaryVariables source(0.0);
        std::fill(energySources_.begin(), energySources_.end(), 0.0);
        for (const auto& element : elements(this->gridGeometry().gridView()))
        {
            const auto fvGeometry = localView(this->gridGeometry()).bindElement(element);
            const auto elemVolVars = localView(gridVars.curGridVolVars()).bindElement(element, fvGeometry, sol);

            for (auto&& scv : scvs(fvGeometry))
            {
                auto pointSources = this->scvPointSources(element, fvGeometry, elemVolVars, scv);
                pointSources += this->source(element, fvGeometry, elemVolVars, scv);
                pointSources *= scv.volume()*elemVolVars[scv].extrusionFactor();
                source += pointSources;

                const auto dofIdxGlobal = scv.dofIndex();
                energySources_[dofIdxGlobal] += pointSources[1];
            }
        }
        std::cout << std::setprecision(12) << "Global integrated source (1D): " << source << '\n';
    }

    void initializeOutput()
    {
        std::ofstream ToutLog;
        ToutLog.open (name_ + ".csv", std::ios::out);
        ToutLog <<"time [d], T [°C]" << std::endl;
        ToutLog.close();
    }

    template <class GridVariables, class TimeLoop, class SolutionVector>
    void writeOutput(const GridVariables& gridVars, const TimeLoop& timeLoop, const SolutionVector& x)
    {
        // obtain current time.
        const Scalar time = timeLoop->time()/3600/24; // convert to days

        for (const auto& element: elements(this->gridGeometry().gridView() ) )
        {
            // we will obtain the current elements local view to get access to the elementVolumeVariables.
            auto fvGeometry = localView(this->gridGeometry() );
            fvGeometry.bind(element);
            auto elemVolVars = localView(gridVars->curGridVolVars() );
            elemVolVars.bindElement(element,fvGeometry,x);
            // we can now iterate over the scvs:
            for (auto&& scv: scvs(fvGeometry))
            {
                if(scv.dofPosition()[0] == this->gridGeometry().bBoxMax()[0])
                {
                    const auto& volVars = elemVolVars[scv];
                    std::ofstream ToutLog;
                    ToutLog.open (name_ + ".csv", std::ios::app);
                    ToutLog << time << "," << volVars.temperature() - 273.15 << std::endl;
                    ToutLog.close();
                }
            }
        }
    }

    void updateNusseltNumbers()
    {
        for(const auto& source : this->couplingManager().lowDimPointSources())
        { nusseltNumbers_[source.elementIndex()] = exchangeFluxCalculator_->getNusseltNumber(source.id()); }
    }

    /*!
     * \brief Adds additional VTK output data to the VTKWriter.
     *
     * Function is called by the output module on every write.
     */
    template<class VtkOutputModule>
    void addVtkOutputFields(VtkOutputModule& vtk) const
    {
        vtk.addField(this->spatialParams().getRadii(), "outer radius", Vtk::FieldType::element);
        vtk.addField(this->spatialParams().getInnerRadii(), "inner radius", Vtk::FieldType::element);
        vtk.addField(nusseltNumbers_, "Nu", Vtk::FieldType::element);
        vtk.addField(energySources_, "energy sources", Vtk::FieldType::vertex);
    }

    //! Get the coupling manager
    const CouplingManager& couplingManager() const
    { return *couplingManager_; }

private:
    static constexpr Scalar eps_ = 1.5e-7;
    Scalar injectionRate_;
    Scalar injectionTemperature_;
    std::string name_;

    std::shared_ptr<CouplingManager> couplingManager_;
    std::shared_ptr<ExchangeFluxCalculator<TypeTag>> exchangeFluxCalculator_;

    std::vector<Scalar> nusseltNumbers_;
    std::vector<Scalar> energySources_;
};

} // end namespace Dumux

#endif
