// -*- mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
// vi: set et ts=4 sw=4 sts=4:
//
// SPDX-FileCopyrightText: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
// SPDX-License-Identifier: GPL-3.0-or-later
//
/*!
 * \file
 * \ingroup BedloadTests
 * \copydoc Dumux::BumpTestProblemShallowWater
 */
#ifndef DUMUX_BUMP_TEST_PROBLEM_SHALLOWWATER_HH
#define DUMUX_BUMP_TEST_PROBLEM_SHALLOWWATER_HH

#include "spatialparams_shallowwater.hh"
#include <dumux/common/parameters.hh>

#include <dumux/freeflow/shallowwater/problem.hh>
#include <dumux/flux/shallowwater/riemannproblem.hh>
#include <dumux/freeflow/shallowwater/boundaryfluxes.hh>

namespace Dumux {

template <class TypeTag>
class BumpTestProblemShallowWater;

/*!
 * \ingroup BedloadTests
 * \brief The problem class for the bump test (shallow water part)
 *
 * This test case involves a weak interaction between flow and mobile bed
 * and has an approximate analytical solution. The test case and the analytical
 * solution can be found in "Numerical Techniqes for Morphodynamic Modelling"
 * Hudson 2001, page 82 ff.
 */
template <class TypeTag>
class BumpTestProblemShallowWater : public ShallowWaterProblem<TypeTag>
{
    using ParentType = ShallowWaterProblem<TypeTag>;
    using PrimaryVariables = GetPropType<TypeTag, Properties::PrimaryVariables>;
    using NumEqVector = Dumux::NumEqVector<PrimaryVariables>;
    using BoundaryTypes = Dumux::BoundaryTypes<GetPropType<TypeTag, Properties::ModelTraits>::numEq()>;
    using Scalar = GetPropType<TypeTag, Properties::Scalar>;
    using ModelTraits = GetPropType<TypeTag, Properties::ModelTraits>;
    using Indices = typename ModelTraits::Indices;
    using GridGeometry = GetPropType<TypeTag, Properties::GridGeometry>;
    using NeumannFluxes = NumEqVector;
    using GridVariables = GetPropType<TypeTag, Properties::GridVariables>;
    using ElementFluxVariablesCache = typename GridVariables::GridFluxVariablesCache::LocalView;
    using ElementVolumeVariables = typename GridVariables::GridVolumeVariables::LocalView;
    using VolumeVariables = typename ElementVolumeVariables::VolumeVariables;
    using FVElementGeometry = typename GridGeometry::LocalView;
    using SubControlVolumeFace = typename FVElementGeometry::SubControlVolumeFace;
    using GridView = typename GridGeometry::GridView;
    using Element = typename GridView::template Codim<0>::Entity;
    using GlobalPosition = typename Element::Geometry::GlobalCoordinate;
    using SubControlVolume = typename FVElementGeometry::SubControlVolume;
    using SolutionVector = GetPropType<TypeTag, Properties::SolutionVector>;

public:
    BumpTestProblemShallowWater(std::shared_ptr<const GridGeometry> gridGeometry,
                                std::shared_ptr<GetPropType<TypeTag, Properties::SpatialParams>> spatialParams)
    : ParentType(gridGeometry, spatialParams)
    {
        name_ = getParam<std::string>("Problem.Name");
        flowRate_ = Dumux::getParam<Scalar>("ShallowWater.FlowRate");
        freeSurfaceOutflow_ = Dumux::getParam<Scalar>("ShallowWater.FreeSurfaceOutflow");
        xBoundaries_ = getParam<std::array<Scalar, 2>>("Grid.Positions0");

        // Set the initial bed surface
        int nElems = gridGeometry->gridView().size(0);
        initialBedSurface_.resize(nElems);
        for (const auto& element : elements(gridGeometry->gridView()))
        {
            auto fvGeometry = localView(this->gridGeometry());
            fvGeometry.bindElement(element);
            for (auto&& scv : scvs(fvGeometry))
            {
            auto elemId = this->gridGeometry().elementMapper().index(element);
            initialBedSurface_[elemId] = this->spatialParams().bedSurface(element, scv);
            }
        }
    }

    /*!
     * \name Problem parameters
     */
    // \{

    /*!
     * \brief The problem name
     *
     * This is used as a prefix for files generated by the simulation.
     */
    const std::string& name() const
    {
        return name_;
    }

     /*!
     * \brief Evaluate the source term for all balance equations within a given
     *        sub-control-volume.
     *
     * There are no sources in this test.
     *
     * \param element The finite element
     * \param fvGeometry The finite-volume geometry
     * \param elemVolVars All volume variables for the element
     * \param scv The sub control volume
     *
     */
     NumEqVector source(const Element& element,
                        const FVElementGeometry& fvGeometry,
                        const ElementVolumeVariables& elemVolVars,
                        const SubControlVolume &scv) const
    {
        NumEqVector values (0.0);

        return values;
    }

    // \}

    /*!
     * \name Boundary conditions
     */
    // \{

    /*!
     * \brief Specifies which kind of boundary condition should be
     *        used for which equation on a given boundary segment.
     *
     * \param globalPos The position for which the boundary type is set
     */
    BoundaryTypes boundaryTypesAtPos(const GlobalPosition &globalPos) const
    {
        BoundaryTypes bcTypes;
        bcTypes.setAllNeumann();
        return bcTypes;
    }

    /*!
     * \brief Specifies the Neumann boundary
     *
     * Specify the Neumann boundary for the shallow water flux.
     *
     * For the shallow water flux we need the Riemann invariants to compute the values depending
     * of the boundary type. Since we use a weak imposition we do not have a Dirichlet value.
     * We impose fluxes based on q, h, etc. computed with the Riemann invariants.
     *
     * \param element The finite element
     * \param fvGeometry The finite-volume geometry
     * \param elemVolVars All volume variables for the element
     * \param scvf The sub control volume face
     */
    NeumannFluxes neumann(const Element& element,
                          const FVElementGeometry& fvGeometry,
                          const ElementVolumeVariables& elemVolVars,
                          const ElementFluxVariablesCache& elemFluxVarsCache,
                          const SubControlVolumeFace& scvf) const
    {
        NeumannFluxes values(0.0);

        const auto& insideScv = fvGeometry.scv(scvf.insideScvIdx());
        const auto& insideVolVars = elemVolVars[insideScv];
        const auto& nxy = scvf.unitOuterNormal();
        const auto gravity = this->spatialParams().gravity(scvf.center());

        // no-flow boundary
        std::array<Scalar, 3> boundaryStateVariables = {0.0};
        auto vNormalGhost = -(nxy[0] * insideVolVars.velocity(0) +  nxy[1] * insideVolVars.velocity(1));
        auto vTangentialGhost = -nxy[1] * insideVolVars.velocity(0) + nxy[0] * insideVolVars.velocity(1);
        // re-rotate to the ghost
        boundaryStateVariables[0] = insideVolVars.waterDepth();
        boundaryStateVariables[1] = nxy[0] * vNormalGhost - nxy[1] * vTangentialGhost;
        boundaryStateVariables[2] = nxy[1] * vNormalGhost + nxy[0] * vTangentialGhost;

        // discharge boundary
        if (scvf.center()[0] < xBoundaries_[0] + eps_)
        {
            boundaryStateVariables = ShallowWater::fixedDischargeBoundary(-flowRate_,
                                                                          insideVolVars.waterDepth(),
                                                                          insideVolVars.velocity(0),
                                                                          insideVolVars.velocity(1),
                                                                          gravity,
                                                                          nxy);
        // free surface boundary
        }else if (xBoundaries_[1] - eps_ < scvf.center()[0])
        {
            boundaryStateVariables =  ShallowWater::fixedWaterDepthBoundary(freeSurfaceOutflow_ - insideVolVars.bedSurface(),
                                                                            insideVolVars.waterDepth(),
                                                                            insideVolVars.velocity(0),
                                                                            insideVolVars.velocity(1),
                                                                            gravity,
                                                                            nxy);
        }

        auto riemannFlux = ShallowWater::riemannProblem(insideVolVars.waterDepth(),
                                                        boundaryStateVariables[0],
                                                        insideVolVars.velocity(0),
                                                        boundaryStateVariables[1],
                                                        insideVolVars.velocity(1),
                                                        boundaryStateVariables[2],
                                                        insideVolVars.bedSurface(),
                                                        insideVolVars.bedSurface(),
                                                        gravity,
                                                        nxy);

        values[Indices::massBalanceIdx] = riemannFlux[0];
        values[Indices::velocityXIdx]   = riemannFlux[1];
        values[Indices::velocityYIdx]   = riemannFlux[2];

        return values;
    }

    /*!
     * \brief Get coupled variables
     *
     * Get h, u and v to exchange them with the bedload model.
     *
     * \param curSol The current solution
     * \param gridVariables The grid variables
     */
    template<class SolutionVector, class GridVariables>
    std::map<std::string, std::vector<Scalar>> getCoupledVariables(const SolutionVector& curSol,
                                                                   const GridVariables& gridVariables)
    {
        int size = this->gridGeometry().gridView().size(0);
        // make map with a string and a vector to store the variable names and their values
        std::map<std::string, std::vector<Scalar>> coupledVariables;
        // add the variable names
        coupledVariables["h"] = std::vector<Scalar>(size, 0.0);
        coupledVariables["u"] = std::vector<Scalar>(size, 0.0);
        coupledVariables["v"] = std::vector<Scalar>(size, 0.0);
        // add the values
        for (const auto& element : elements(this->gridGeometry().gridView()))
        {
            auto fvGeometry = localView(this->gridGeometry());
            fvGeometry.bindElement(element);

            auto elemVolVars = localView(gridVariables.curGridVolVars());
            elemVolVars.bindElement(element, fvGeometry, curSol);

            // get local index of the element
            const auto eIdx = this->gridGeometry().elementMapper().index(element);
            // we loop over the gost entities, too
            for (auto&& scv : scvs(fvGeometry))
            {
                coupledVariables["h"][eIdx] = elemVolVars[scv].waterDepth();
                coupledVariables["u"][eIdx] = elemVolVars[scv].velocity(0);
                coupledVariables["v"][eIdx] = elemVolVars[scv].velocity(1);
            }
        }
        return coupledVariables;
    }
    // \}

    /*!
     * \name Volume terms
     */
    // \{

    /*!
     * \brief Evaluate the initial values for a control volume.
     *
     * For this method, the \a values parameter stores primary variables.
     *
     * \param element The finite element
     */
    PrimaryVariables initial(const Element& element) const
    {
        PrimaryVariables values(0.0);
        auto elemId = this->gridGeometry().elementMapper().index(element);

        Scalar waterDepth = freeSurfaceOutflow_ - initialBedSurface_[elemId];

        values[0] = waterDepth;
        values[1] = flowRate_ / waterDepth;
        values[2] = 0.0;

        return values;
    }

    // \}

private:
    static constexpr Scalar eps_ = 1.0e-6;   // [-]
    Scalar flowRate_;                        // [m^2/s]
    Scalar freeSurfaceOutflow_;              // [m]
    std::vector<Scalar> initialBedSurface_;  // [m]
    std::string name_;
    std::array<Scalar, 2> xBoundaries_;
};

} //end namespace Dumux

#endif
