Module: dumux
Version: 3.5-git
Author: The DuMux Team
Maintainer: dumux@listserv.uni-stuttgart.de
Depends: dune-common (>=2.8) dune-grid (>=2.8) dune-localfunctions (>=2.8) dune-istl (>=2.8)
Suggests: dune-alugrid (>=2.8) dune-foamgrid (>=2.8) dune-uggrid (>=2.8) dune-functions (>=2.8) opm-common opm-grid dune-subgrid (>=2.8) dune-spgrid (>=2.8) dune-mmesh (>=1.2)
Description: DuMux is a module for simulation of multi-phase multi-component flow transport in porous media
URL: https://dumux.org
Python-Requires:
Whitespace-Hook: Yes
