Module: dumux
Version: 3.4-git
Author: The DuMux Team
Maintainer: dumux@listserv.uni-stuttgart.de
Depends: dune-common (>= 2.7) dune-grid (>= 2.7) dune-localfunctions (>= 2.7) dune-istl (>= 2.7)
Suggests: dune-alugrid (>=2.7) dune-foamgrid (>=2.7) dune-uggrid (>=2.7) dune-functions (>=2.7) opm-common opm-grid dune-subgrid dune-spgrid (>= 2.7) dune-mmesh (>= 1.1)
Description: DuMux is a module for simulation of multi-phase multi-component flow transport in porous media
URL: https://dumux.org
Python-Requires:
Whitespace-Hook: Yes
