default:
  image: $IMAGE

stages:
  - build
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE=="parent_pipeline"

variables:
  TRIGGER_SOURCE: "unknown"

build dumux:
  stage: build
  script:
    - |
      mkdir dune && cd dune
      git clone -b releases/2.7 https://gitlab.dune-project.org/core/dune-common
      git clone -b releases/2.7 https://gitlab.dune-project.org/core/dune-geometry
      git clone -b releases/2.7 https://gitlab.dune-project.org/core/dune-grid
      git clone -b releases/2.7 https://gitlab.dune-project.org/core/dune-istl
      git clone -b releases/2.7 https://gitlab.dune-project.org/core/dune-localfunctions
      cd ..
      ./dune/dune-common/bin/dunecontrol --opts=cmake.opts all
      cd build-cmake
      make -j8 build_tests
  artifacts:
    paths:
      - dune
      - build-cmake
    expire_in: 3 hours

test dumux:
  stage: test
  variables:
    OMPI_ALLOW_RUN_AS_ROOT: 1
    OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  script:
    - |
      cd build-cmake
      ctest -j8 build_tests --output-on-failure
  needs:
    - job: build dumux
      artifacts: true
  artifacts:
    reports:
      junit: junit/dumux-cmake.xml
