default:
  image: $IMAGE

stages:
  - configure
  - build
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE=="parent_pipeline"

variables:
  TRIGGER_SOURCE: "unknown"

select tests:
  stage: configure
  image: $IMAGE_REGISTRY_URL/full:dune-2.7-gcc-ubuntu-20.04
  script:
    - |
      echo "Skipping test selection, build/test stages will consider all tests!"
      echo "{}" >> affectedtests.json
  artifacts:
    paths:
      - affectedtests.json
    expire_in: 3 hours

build dumux:
  stage: build
  script:
    - dunecontrol --opts=$DUNE_OPTS_FILE --current all
    - |
      pushd build-cmake
          python3 ../bin/testing/runselectedtests.py --all -b
      popd
  artifacts:
    paths:
      - build-cmake
      - affectedtests.json
    expire_in: 3 hours
  needs:
    - job: select tests
      artifacts: true

test dumux:
  stage: test
  variables:
    OMPI_ALLOW_RUN_AS_ROOT: 1
    OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  script:
    - |
      pushd build-cmake
          python3 ../bin/testing/runselectedtests.py --all -t
      popd
  needs:
    - job: build dumux
      artifacts: true
  artifacts:
    reports:
      junit: junit/dumux-cmake.xml
