// -*- mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
// vi: set et ts=4 sw=4 sts=4:
//
// SPDX-FileCopyrightText: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
// SPDX-License-Identifier: GPL-3.0-or-later
//
/*!
 * \file
 * \ingroup ShallowWaterTests
 * \brief A test for the shallow water model (lake at rest).
 */
#ifndef DUMUX_LAKE_AT_REST_TEST_PROBLEM_HH
#define DUMUX_LAKE_AT_REST_TEST_PROBLEM_HH

#include <algorithm>
#include <string>

#include <dumux/common/boundarytypes.hh>
#include <dumux/common/properties.hh>
#include <dumux/common/parameters.hh>
#include <dumux/common/numeqvector.hh>

#include <dumux/freeflow/shallowwater/problem.hh>
#include <dumux/freeflow/shallowwater/boundaryfluxes.hh>

namespace Dumux {

/*!
 * \ingroup ShallowWaterTests
 * \brief The lake-at-rest (well-balancing) test.
 *
 * Water at rest over a variable bed is a steady state of the shallow water equations:
 * for a horizontal free surface \f$ h + z = H \f$ and zero velocity the pressure part of
 * the momentum flux is balanced exactly by the bed slope source term. A scheme that
 * reproduces this state up to round-off is called well-balanced, or is said to satisfy
 * the C-property (Bermudez and Vazquez, "Upwind methods for hyperbolic conservation laws
 * with source terms", Computers & Fluids, 23(8):1049-1071, 1994,
 * doi: https://doi.org/10.1016/0045-7930(94)90004-3). Schemes that are not well-balanced
 * generate spurious velocities of the order of the bed variation, which can dominate the
 * physical signal in applications with rough bathymetry.
 *
 * The exact solution is the initial condition, so the test measures the deviation from it
 * directly and does not need a reference solution.
 *
 * Where the bed emerges from the lake, the water depth is set to \c Problem.MinWaterDepth
 * instead of zero. A completely dry cell has no momentum storage, \f$ \partial (hu) /
 * \partial u = h = 0 \f$, which makes the Jacobian singular. The thin film that avoids
 * this is not a state of rest itself and limits the accuracy that can be reached on a
 * partially dry bed to the order of the film thickness.
 *
 * There is no flow over the boundaries and no friction is considered.
 *
 * This problem uses the \ref ShallowWaterModel.
 */
template <class TypeTag>
class LakeAtRestProblem : public ShallowWaterProblem<TypeTag>
{
    using ParentType = ShallowWaterProblem<TypeTag>;

    using GridGeometry = GetPropType<TypeTag, Properties::GridGeometry>;
    using FVElementGeometry = typename GridGeometry::LocalView;
    using SubControlVolumeFace = typename FVElementGeometry::SubControlVolumeFace;
    using GridView = typename GridGeometry::GridView;
    using Element = typename GridView::template Codim<0>::Entity;
    using GlobalPosition = typename Element::Geometry::GlobalCoordinate;

    using Scalar = GetPropType<TypeTag, Properties::Scalar>;
    using PrimaryVariables = GetPropType<TypeTag, Properties::PrimaryVariables>;
    using NumEqVector = Dumux::NumEqVector<PrimaryVariables>;

    using NeumannFluxes = NumEqVector;
    using ElementVolumeVariables = typename GetPropType<TypeTag, Properties::GridVolumeVariables>::LocalView;
    using Indices = typename GetPropType<TypeTag, Properties::ModelTraits>::Indices;
    using BoundaryTypes = Dumux::BoundaryTypes<GetPropType<TypeTag, Properties::ModelTraits>::numEq()>;

public:
    LakeAtRestProblem(std::shared_ptr<const GridGeometry> gridGeometry)
    : ParentType(gridGeometry)
    , name_(getParam<std::string>("Problem.Name"))
    , waterLevel_(getParam<Scalar>("Problem.WaterLevel"))
    , minWaterDepth_(getParam<Scalar>("Problem.MinWaterDepth", 0.0))
    {}

    //! The water depth of the lake at rest
    Scalar exactWaterDepthAtPos(const GlobalPosition& globalPos) const
    {
        using std::max;
        return max(waterLevel_ - this->spatialParams().bedSurfaceAtPos(globalPos), minWaterDepth_);
    }

    /*!
     * \name Problem parameters
     */
    // \{

    /*!
     * \brief The problem name
     * This is used as a prefix for files generated by the simulation.
     */
    const std::string& name() const
    { return name_; }

    // \}

    /*!
     * \name Boundary conditions
     */
    // \{

    /*!
     * \brief Specifies which kind of boundary condition should be
     *        used for which equation on a given boundary segment.
     */
    BoundaryTypes boundaryTypesAtPos(const GlobalPosition &globalPos) const
    {
        BoundaryTypes bcTypes;
        bcTypes.setAllNeumann();
        return bcTypes;
    }

    /*!
     * \brief Specifies the neumann boundary
     *
     *  We need the Riemann invariants to compute the values depending of the boundary type.
     *  Since we use a weak imposition we do not have a dirichlet value. We impose fluxes
     *  based on q, h, etc. computed with the Riemann invariants
     */
    template<class ElementFluxVariablesCache>
    NeumannFluxes neumann(const Element& element,
                          const FVElementGeometry& fvGeometry,
                          const ElementVolumeVariables& elemVolVars,
                          const ElementFluxVariablesCache& elemFluxVarsCache,
                          const SubControlVolumeFace& scvf) const
    {
        NeumannFluxes values(0.0);

        const auto& insideScv = fvGeometry.scv(scvf.insideScvIdx());
        const auto& insideVolVars = elemVolVars[insideScv];
        const auto& nxy = scvf.unitOuterNormal();
        const auto gravity = this->spatialParams().gravity(scvf.center());

        const auto boundaryStateVariables = ShallowWater::wallBoundary(insideVolVars.waterDepth(),
                                                                       insideVolVars.velocity(0),
                                                                       insideVolVars.velocity(1),
                                                                       nxy);

        const auto riemannFlux =
            ShallowWater::riemannProblem(insideVolVars.waterDepth(), boundaryStateVariables[0],
                                         insideVolVars.velocity(0), boundaryStateVariables[1],
                                         insideVolVars.velocity(1), boundaryStateVariables[2],
                                         insideVolVars.bedSurface(), insideVolVars.bedSurface(),
                                         gravity, nxy);

        values[Indices::massBalanceIdx] = riemannFlux[0];
        values[Indices::velocityXIdx]   = riemannFlux[1];
        values[Indices::velocityYIdx]   = riemannFlux[2];

        return values;
    }

    // \}

    /*!
     * \name Volume terms
     */
    // \{

    /*!
     * \brief Evaluate the initial values at position globalPos
     */
    PrimaryVariables initialAtPos(const GlobalPosition& globalPos) const
    { return { exactWaterDepthAtPos(globalPos), 0.0, 0.0 }; }

    // \}

private:
    std::string name_;
    Scalar waterLevel_;
    Scalar minWaterDepth_;
};

} // end namespace Dumux

#endif
