# SPDX-FileCopyrightText: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
# SPDX-License-Identifier: GPL-3.0-or-later

add_subdirectory(boundaryfluxes)
add_subdirectory(bowl)
add_subdirectory(dambreak)
add_subdirectory(iofields)
add_subdirectory(lakeatrest)
add_subdirectory(poiseuilleflow)
add_subdirectory(roughchannel)
