#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
# SPDX-License-Identifier: GPL-3.0-or-later
"""Plot convergence and 3D deformation for any plate test.

Usage (run from the test subdirectory, e.g. kirchhoff_love/):
  python3 ../plot_convergence.py <executable>
"""

import glob
import os
import sys
import numpy as np
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from convergencetest import collect_data, compute_rates, print_table

if len(sys.argv) < 2:
    sys.stderr.write("Usage: python3 plot_convergence.py <executable>\n")
    sys.exit(1)

testname = str(sys.argv[1])
exe_basename = os.path.basename(testname)

# Derive plot title from executable name: "test_kirchhoff_love_plate" -> "Kirchhoff Love Plate"
title_words = exe_basename.removeprefix("test_").replace("_", " ").title()
title = f"{title_words}: convergence of vertical deformation"

hs, errors = collect_data(testname, [0.25, 0.125, 0.0625, 0.03125])
rates = compute_rates(hs, errors)
print_table(hs, errors, rates)

fig, ax = plt.subplots(figsize=(6, 4))
ax.loglog(hs, errors, "o-", label="L² error")

ref_x = np.array([hs[0], hs[-1]])
ref_y = errors[0] * (ref_x / hs[0]) ** 2
ax.loglog(ref_x, ref_y, "k--", label=r"$\mathcal{O}(h^2)$")

ax.set_xlabel("mesh size $h$")
ax.set_ylabel(r"relative $L^2$ error in $w$")
ax.set_title(title)
ax.legend()
ax.grid(True, which="both", alpha=0.3)
fig.tight_layout()
fig.savefig("convergence.png", dpi=150)
print("Saved convergence.png")
plt.show()

# 3D deformation plot using the finest-mesh VTK output
try:
    import pyvista as pv

    pvd_file = exe_basename + ".pvd"
    reader = pv.get_reader(pvd_file)
    reader.set_active_time_value(reader.time_values[-1])
    mesh = reader.read()[0]

    w_max = float(np.abs(mesh["w"]).max())
    scale = 0.5 / w_max if w_max > 0 else 1.0

    warped = mesh.warp_by_scalar("w", factor=scale, normal=[0, 0, 1])

    pl = pv.Plotter(off_screen=True)
    pl.add_mesh(warped, scalars="w", cmap="RdBu_r", scalar_bar_args={"title": "w"})
    pl.view_isometric()
    pl.screenshot("deformation_3d.png")
    print("Saved deformation_3d.png")
except Exception as e:
    print(f"3D plot skipped: {e}")

# Clean up VTK output generated by the executable
for f in glob.glob(exe_basename + "*.vtu") + [exe_basename + ".pvd"]:
    if os.path.exists(f):
        os.remove(f)
