// -*- mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
// vi: set et ts=4 sw=4 sts=4:
/*****************************************************************************
 *   See the file COPYING for full copying permissions.                      *
 *                                                                           *
 *   This program is free software: you can redistribute it and/or modify    *
 *   it under the terms of the GNU General Public License as published by    *
 *   the Free Software Foundation, either version 3 of the License, or       *
 *   (at your option) any later version.                                     *
 *                                                                           *
 *   This program is distributed in the hope that it will be useful,         *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of          *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the            *
 *   GNU General Public License for more details.                            *
 *                                                                           *
 *   You should have received a copy of the GNU General Public License       *
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.   *
 *****************************************************************************/
/*!
 * \file
 * \ingroup TwoPNCNCPTests
 * \brief
 */
#ifndef DUMUX_2PNC_NCP_PROBLEM_HH
#define DUMUX__2PNC_NCP_PROBLEM_HH

#include <dumux/common/properties.hh>
#include <dumux/common/parameters.hh>
#include <dumux/common/boundarytypes.hh>
#include <dumux/common/numeqvector.hh>

#include <dumux/porousmediumflow/problem.hh>
#include <dumux/material/constraintsolvers/computefromreferencephase.hh>

namespace Dumux {

/*!
 * \ingroup TwoPNCNCPTests
 * \brief
 *
 * This problem uses the \ref TwoPNCNCPModel.
 */
template <class TypeTag>
class TwoPNCSaltProblem
    : public PorousMediumFlowProblem<TypeTag>
{
    using ParentType = PorousMediumFlowProblem<TypeTag>;
    using Scalar = GetPropType<TypeTag, Properties::Scalar>;
    using FluidSystem = GetPropType<TypeTag, Properties::FluidSystem>;
    using BoundaryTypes = Dumux::BoundaryTypes<GetPropType<TypeTag, Properties::ModelTraits>::numEq()>;
    using PrimaryVariables = GetPropType<TypeTag, Properties::PrimaryVariables>;
    using NumEqVector = Dumux::NumEqVector<PrimaryVariables>;
    using ElementVolumeVariables = typename GetPropType<TypeTag, Properties::GridVolumeVariables>::LocalView;
    using FVElementGeometry = typename GetPropType<TypeTag, Properties::GridGeometry>::LocalView;
    using SubControlVolume = typename FVElementGeometry::SubControlVolume;
    using SubControlVolumeFace = typename FVElementGeometry::SubControlVolumeFace;
    using GridView = typename GetPropType<TypeTag, Properties::GridGeometry>::GridView;
    using Element = typename GridView::template Codim<0>::Entity;
    using GridGeometry = GetPropType<TypeTag, Properties::GridGeometry>;
    using FluidState = GetPropType<TypeTag, Properties::FluidState>;
    using ParameterCache = typename FluidSystem::ParameterCache;

    using ModelTraits = GetPropType<TypeTag, Properties::ModelTraits>;
    using Indices = typename ModelTraits::Indices;

    enum { dimWorld = GridView::dimensionworld };
    enum { numPhases = ModelTraits::numFluidPhases() };
    enum { numComponents = ModelTraits::numFluidComponents() };
    enum { gasPhaseIdx = FluidSystem::gasPhaseIdx };
    enum { liquidPhaseIdx = FluidSystem::liquidPhaseIdx };
    enum { H2OIdx = FluidSystem::H2OIdx };
    enum { AirIdx = FluidSystem::AirIdx };
    enum { NaClIdx = FluidSystem::NaClIdx };
    enum { comp0Idx = Indices::comp0Idx };
    enum { s0Idx = Indices::saturationIdx };
    enum { p0Idx = Indices::pressureIdx };

    using GlobalPosition = typename SubControlVolume::GlobalPosition;
    using PhaseVector = Dune::FieldVector<Scalar, numPhases>;

public:
    TwoPNCSaltProblem(std::shared_ptr<const GridGeometry> gridGeometry)
        : ParentType(gridGeometry)
    {
        temperature_ = 273.15 + 25; // -> 25°C

        // initialize the tables of the fluid system
        Scalar Tmin = temperature_ - 1.0;
        Scalar Tmax = temperature_ + 1.0;
        int nT = 3;

        Scalar pmin = 1.0e5 * 0.75;
        Scalar pmax = 2.0e5 * 1.25;
        int np = 1000;

        FluidSystem::init(Tmin, Tmax, nT, pmin, pmax, np);
        name_ = getParam<std::string>("Problem.Name");
    }

    /*!
     * \name Problem parameters
     */
    // \{

    /*!
     * \brief Returns the problem name
     *
     * This is used as a prefix for files generated by the simulation.
     */
    const std::string name() const
    { return name_; }

    /*!
     * \brief Returns the temperature \f$ K \f$
     */
    Scalar temperature() const
    { return temperature_; }

    // \}

    /*!
     * \name Boundary conditions
     */
    // \{
    /*!
     * \brief Specifies which kind of boundary condition should be
     *        used for which equation on a given boundary segment
     *
     * \param globalPos The global position
     */
    BoundaryTypes boundaryTypesAtPos(const GlobalPosition &globalPos) const
    {
        BoundaryTypes bcTypes;
        if (onInlet_(globalPos) || onOutlet_(globalPos))
            bcTypes.setAllDirichlet();
        else
            bcTypes.setAllNeumann();
        return bcTypes;
    }

    /*!
     * \brief Evaluates the boundary conditions for a Dirichlet boundary segment.
     *
     * \param globalPos The global position
     */
    PrimaryVariables dirichletAtPos(const GlobalPosition &globalPos) const
    {
       return initial_(globalPos);
    }

    /*!
     * \brief Evaluates the boundary conditions for a Neumann boundary segment.
     */
    NumEqVector neumannAtPos(const GlobalPosition& globalPos) const
    {
        return NumEqVector(0.0);
    }

    // \}

    /*!
     * \name Volume terms
     */
    // \{

    /*!
     * \brief Evaluates the source term for all balance equations within a given
     *        sub-control volume.
     *
     * \param element The finite element
     * \param fvGeometry The finite volume geometry of the element
     * \param elemVolVars The volume variables of the element
     * \param scv The sub-control volume
     *
     * Positive values mean that mass is created, negative ones mean that it vanishes.
     */
    NumEqVector source(const Element &element,
                       const FVElementGeometry& fvGeometry,
                       const ElementVolumeVariables& elemVolVars,
                       const SubControlVolume &scv) const
    {
       return NumEqVector(0.0);
    }

    /*!
     * \brief Evaluates the initial value for a control volume.
     *
     * \param globalPos The center of the finite volume which ought to be set.
     *
     * For this method, the \a values parameter stores primary
     * variables.
     */
    PrimaryVariables initialAtPos(const GlobalPosition &globalPos) const
    {
        return initial_(globalPos);
    }

    // \}

private:
    // the internal method for the initial condition
    PrimaryVariables initial_(const GlobalPosition &globalPos) const
    {
        PrimaryVariables values(0.0);
        values.setState(Indices::bothPhases);
        FluidState fs;

        int refPhaseIdx;
        int otherPhaseIdx;

        // set the fluid temperatures
        fs.setTemperature(this->temperatureAtPos(globalPos));

        refPhaseIdx = liquidPhaseIdx;
        otherPhaseIdx = gasPhaseIdx;

        if (onInlet_(globalPos))
        {

            // set liquid saturation
            fs.setSaturation(liquidPhaseIdx, 0.5);

            // set pressure of the liquid phase
            fs.setPressure(liquidPhaseIdx, 1.1e5);

            // set the liquid composition to pure water
            //fs.setMoleFraction(liquidPhaseIdx, AirIdx, 0.0);
            //fs.setMoleFraction(liquidPhaseIdx, H2OIdx, 1.0-0.04);
            fs.setMoleFraction(liquidPhaseIdx, NaClIdx, 0.04);
        }
        else {
            // set gas saturation
            fs.setSaturation(liquidPhaseIdx, 0.5);

            // set pressure of the gas phase
            fs.setPressure(liquidPhaseIdx, 1e5);

            //fs.setMoleFraction(liquidPhaseIdx, AirIdx, 0.0);
            //fs.setMoleFraction(liquidPhaseIdx, H2OIdx, 1.0-0.03);
            fs.setMoleFraction(liquidPhaseIdx, NaClIdx, 0.03);
        }

        // set the other saturation
        fs.setSaturation(otherPhaseIdx, 1.0 - fs.saturation(refPhaseIdx));

        // calculate the capillary pressure
        const auto fluidMatrixInteraction = this->spatialParams().fluidMatrixInteractionAtPos(globalPos);
        const int wPhaseIdx = this->spatialParams().template wettingPhaseAtPos<FluidSystem>(globalPos);
        const auto pc = fluidMatrixInteraction.pc(fs.saturation(wPhaseIdx));
        fs.setPressure(otherPhaseIdx,
                       fs.pressure(refPhaseIdx)
                       + pc);

        // make the fluid state consistent with local thermodynamic
        // equilibrium
        // make the fluid state consistent with local thermodynamic
        // equilibrium
        using MiscibleMultiPhaseComposition = Dumux::MiscibleMultiPhaseComposition<Scalar, FluidSystem>;

        ParameterCache paramCache;
        MiscibleMultiPhaseComposition::solve(fs, paramCache);


        ///////////
        // assign the primary variables
        ///////////

        // all N component fugacities
        for (int compIdx = 0; compIdx < numComponents-1; ++compIdx)
        {
            values[comp0Idx + compIdx] = fs.moleFraction(refPhaseIdx, compIdx);
            //std::cout<<"molefrac "<< values[comp0Idx + compIdx]<<" comp "<<compIdx<<std::endl;
        }

        if (onInlet_(globalPos))
            values[comp0Idx + 2] = 0.04;
        else
            values[comp0Idx + 2] = 0.03;

        values[Indices::saturationIdx] = fs.saturation(1);

        // first pressure
        values[p0Idx] = fs.pressure(/*phaseIdx=*/0);
        return values;
    }

    bool onInlet_(const GlobalPosition &globalPos) const
    {
        Scalar x = globalPos[0];
        Scalar y = globalPos[1];
        return x >= 60 - eps_ && y <= 10 + eps_;
    }

    bool onOutlet_(const GlobalPosition &globalPos) const
    {
        Scalar x = globalPos[0];
        Scalar y = globalPos[1];
        return x < eps_ && y <= 10 + eps_;
    }

    Scalar temperature_;
    static constexpr Scalar eps_ = 1e-6;
    std::string name_;
};
} // end namespace Dumux

#endif
