flowchart LR
    B -->|"assembleJacobianAndResidual()"| D(localAssembler)
    D -->|"evalFluxAndSourceResidual()"| E(localResidual)
    D -->|"evalStorageResidual()"| E
    click B "./assembler.html"
    click D "./localassembler.html"
    click E "./localresidual.html"
