// -*- mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
// vi: set et ts=4 sw=4 sts=4:
//
// SPDX-FileCopyrightText: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
// SPDX-License-Identifier: GPL-3.0-or-later
//
/*!
 * \file
 * \ingroup BedloadTests
 * \copydoc Dumux::ChannelBendTestProblemBedload
 */
#ifndef DUMUX_CHANNEL_BEND_TEST_PROBLEM_BEDLOAD_HH
#define DUMUX_CHANNEL_BEND_TEST_PROBLEM_BEDLOAD_HH

#include "spatialparams_bedload.hh"
#include <dumux/common/parameters.hh>

#include <dumux/freeflow/bedload/problem.hh>
#include <dumux/material/sediment/layermodels/layermodel.hh>
#include <dumux/material/sediment/layermodels/hirano.hh>

namespace Dumux {

template <class TypeTag>
class ChannelBendTestProblemBedload;

/*!
 * \ingroup BedloadTests
 * \brief The problem class for the channel bend test (bedload part)
 *
 * This test is based on run number four of the experiments presented in
 * Yen and Lee (1995) "Bed topography and sediment sorting in channel bend
 * with unsteady flow", Journal of Hydraulic Engineering.
 */
template <class TypeTag>
class ChannelBendTestProblemBedload : public BedloadProblem<TypeTag>
{
    using ParentType = BedloadProblem<TypeTag>;
    using PrimaryVariables = GetPropType<TypeTag, Properties::PrimaryVariables>;
    using NumEqVector = Dumux::NumEqVector<PrimaryVariables>;
    using BoundaryTypes = Dumux::BoundaryTypes<GetPropType<TypeTag, Properties::ModelTraits>::numEq()>;
    using Scalar = GetPropType<TypeTag, Properties::Scalar>;
    using ModelTraits = GetPropType<TypeTag, Properties::ModelTraits>;
    using Indices = typename ModelTraits::Indices;
    using GridGeometry = GetPropType<TypeTag, Properties::GridGeometry>;
    using NeumannFluxes = NumEqVector;
    using GridVariables = GetPropType<TypeTag, Properties::GridVariables>;
    using ElementFluxVariablesCache = typename GridVariables::GridFluxVariablesCache::LocalView;
    using ElementVolumeVariables = typename GridVariables::GridVolumeVariables::LocalView;
    using VolumeVariables = typename ElementVolumeVariables::VolumeVariables;
    using FVElementGeometry = typename GridGeometry::LocalView;
    using SubControlVolumeFace = typename FVElementGeometry::SubControlVolumeFace;
    using GridView = typename GridGeometry::GridView;
    using Element = typename GridView::template Codim<0>::Entity;
    using GlobalPosition = typename Element::Geometry::GlobalCoordinate;
    using SubControlVolume = typename FVElementGeometry::SubControlVolume;
    using SolutionVector = GetPropType<TypeTag, Properties::SolutionVector>;
    using LayerModelType = typename std::shared_ptr<LayerModel<GridGeometry, GetPropType<TypeTag, Properties::SpatialParams>,
                                                    VolumeVariables, SolutionVector, GridVariables>>;

public:
    ChannelBendTestProblemBedload(std::shared_ptr<const GridGeometry> gridGeometry,
                                  std::shared_ptr<GetPropType<TypeTag, Properties::SpatialParams>> spatialParams,
                                  std::vector<Scalar>& initialBedSurface)
    : ParentType(gridGeometry, spatialParams)
    {
        initialBedSurface_ = initialBedSurface;

        name_ = getParam<std::string>("Problem.Name");
        nGrainClasses_ = Dumux::getParam<int>("Sediment.NumberGrainClasses");
        if (nGrainClasses_ != TypeTag::nGrainClasses) {
            DUNE_THROW(Dune::InvalidStateException, "Please set 'Sediment.NumberGrainClasses = 3'.");
        }
        nLayers_ = Dumux::getParam<int>("Sediment.NumberLayers");
        if (nLayers_ != 2) {
            DUNE_THROW(Dune::InvalidStateException, "Please set 'Sediment.NumberLayers = 2'.");
        }

        // define the layer model
        layerModel_ = std::make_unique<LayerModelHirano<GridGeometry, GetPropType<TypeTag, Properties::SpatialParams>, VolumeVariables,
                                                        SolutionVector, GridVariables>>(gridGeometry, spatialParams);
    }

    //! Update the layer model
    template<class SolutionVector, class GridVariables>
    void updateLayerModel(SolutionVector& curSol,
                          const GridVariables& gridVariables)
    {
        layerModel_->update(curSol, gridVariables);
    }

    /*!
     * \name Problem parameters
     */
    // \{

    /*!
     * \brief The problem name
     *
     * This is used as a prefix for files generated by the simulation.
     */
    const std::string& name() const
    {
        return name_;
    }

     /*!
     * \brief Evaluate the source term for all balance equations within a given
     *        sub-control-volume.
     *
     * There are no sources in this test. In general, a source could be artificial
     * sediment feeding or suspended load.
     *
     * For this method, the \a values parameter stores the conserved quantity rate
     * generated or annihilate per volume unit. Positive values mean
     * that the conserved quantity is created, negative ones mean that it vanishes.
     * E.g. for the sediment mass balance that would be a mass rate in \f$ [ kg / (m^3 \cdot s)] \f$.
     *
     * \param element The finite element
     * \param fvGeometry The finite-volume geometry
     * \param elemVolVars All volume variables for the element
     * \param scv The sub control volume
     *
     */
     NumEqVector source(const Element& element,
                        const FVElementGeometry& fvGeometry,
                        const ElementVolumeVariables& elemVolVars,
                        const SubControlVolume &scv) const
    {
        NumEqVector values (0.0);

        return values;
    }

    // \}

    /*!
     * \name Boundary conditions
     */
    // \{

    /*!
     * \brief Specifies which kind of boundary condition should be
     *        used for which equation on a given boundary segment.
     *
     * \param globalPos The position for which the boundary type is set
     */
    BoundaryTypes boundaryTypesAtPos(const GlobalPosition &globalPos) const
    {
        BoundaryTypes bcTypes;
        bcTypes.setAllNeumann();
        return bcTypes;
    }

    /*!
     * \brief Specifies the Neumann boundary
     *
     * Specify the Neumann boundary for the bedload flux.
     *
     * For the bedload flux we implement a euqilibrium boundary condition. This means that as much sediment enters
     * or leaves the domain as is tranported in the corresponding boundary cell.
     *
     * \param element The finite element
     * \param fvGeometry The finite-volume geometry
     * \param elemVolVars All volume variables for the element
     * \param scvf The sub control volume face
     */
    NeumannFluxes neumann(const Element& element,
                          const FVElementGeometry& fvGeometry,
                          const ElementVolumeVariables& elemVolVars,
                          const ElementFluxVariablesCache& elemFluxVarsCache,
                          const SubControlVolumeFace& scvf) const
    {
        NeumannFluxes values(0.0);

        const auto& insideScv = fvGeometry.scv(scvf.insideScvIdx());
        const auto& insideVolVars = elemVolVars[insideScv];
        const auto& nxy = scvf.unitOuterNormal();

        // inflow: bedload equilibrium boundary
        if (scvf.center()[1] < yMin_ + eps_ && scvf.center()[0] < xCenter_)
        {
            for (int i=0; i<nGrainClasses_; i++)
            {
                const auto bedloadDischarge = this->spatialParams().bedloadFormula(i).bedloadDischarge(insideVolVars);
                const auto normalBedloadDischarge = bedloadDischarge[0] * nxy[0] + bedloadDischarge[1] * nxy[1];
                // Scale the potential bedload discharge with the mass fraction to get the actual bedload discharge of
                // the corresponding grain class. At the inflow the initial mass fraction is used to scale the inflow.
                // Otherwise small pertubation can cause problems.
                Scalar scalingFactor = layerModel_->initialMassFractionsActiveLayer(element, i);
                values[i] = normalBedloadDischarge * scalingFactor * this->spatialParams().grainDensity(i);
            }
        }
        // outflow: bedload equilibrium boundary
        else if (scvf.center()[1] < yMin_ + eps_ && scvf.center()[0] > xCenter_)
        {
            for (int i=0; i<nGrainClasses_; i++)
            {
                const auto bedloadDischarge = this->spatialParams().bedloadFormula(i).bedloadDischarge(insideVolVars);
                const auto normalBedloadDischarge = bedloadDischarge[0] * nxy[0] + bedloadDischarge[1] * nxy[1];
                // Scale the potential bedload discharge with the mass fraction to get the actual bedload discharge of
                // the corresponding grain class. At the outflow the current mass fraction is used to scale the outflow,
                // to allow variation of sediment composition.
                Scalar scalingFactor = insideVolVars.massFraction(i);
                values[i] = normalBedloadDischarge * scalingFactor * this->spatialParams().grainDensity(i);
            }
        }
        return values;
    }

    /*!
     * \brief Get coupled variables
     *
     * Get the bed surface for exchange with the shallow water model.
     *
     * \param curSol The current solution
     * \param gridVariables The grid variables
     */
    template<class SolutionVector, class GridVariables>
    std::map<std::string, std::vector<Scalar>> getCoupledVariables(const SolutionVector& curSol,
                                                                   const GridVariables& gridVariables)
    {
        int size = this->gridGeometry().gridView().size(0);
        // make map with a string and a vector to store the variable names and their values
        std::map<std::string, std::vector<Scalar>> coupledVariables;
        // add the variable names
        coupledVariables["bedSurface"] = std::vector<Scalar>(size, 0.0);
        // add the values
        for (const auto& element : elements(this->gridGeometry().gridView()))
        {
            auto fvGeometry = localView(this->gridGeometry());
            fvGeometry.bindElement(element);

            auto elemVolVars = localView(gridVariables.curGridVolVars());
            elemVolVars.bindElement(element, fvGeometry, curSol);

            // get local index of the element
            const auto eIdx = this->gridGeometry().elementMapper().index(element);
            // loop over the ghost entities, too
            for (auto&& scv : scvs(fvGeometry))
            {
                coupledVariables["bedSurface"][eIdx] = elemVolVars[scv].bedSurface();
            }
        }
        return coupledVariables;
    }

    // \}

    /*!
     * \name Volume terms
     */
    // \{

    /*!
     * \brief Evaluate the initial values for a control volume.
     *
     * For this method, the \a values parameter stores primary variables.
     *
     * \param element The finite element
     */
    PrimaryVariables initial(const Element& element) const
    {
        PrimaryVariables values(0.0);
        for (int i=0; i<nGrainClasses_; i++) {
            values[i] = layerModel_->initialSedimentMassActiveLayer(element, i);
        }
        return values;
    }

    // \}

    /*!
     * \brief Return the bottom of the active layer of an element.
     *
     * \param element The finite element
     */
    const Scalar bottomActiveLayer(const Element& element,
                                   const SubControlVolume& scv) const
    {
        return layerModel_->bottomActiveLayer(element);
    }

private:
    Scalar bedloadBoundaryDischarge_ = 0.0;    // [kg/s]
    static constexpr Scalar eps_ = 1.0e-6;     // [-]
    std::vector<Scalar> initialBedSurface_;    // [m]
    LayerModelType layerModel_;
    std::string name_;
    int nGrainClasses_;                        // [-]
    int nLayers_;                              // [-]
    Scalar xCenter_ = 101.1819;                // [m]
    Scalar yMin_ = 31.1371;                    // [m]
};

} //end namespace Dumux

#endif
