// -*- mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
// vi: set et ts=4 sw=4 sts=4:
//
// SPDX-FileCopyrightText: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
// SPDX-License-Identifier: GPL-3.0-or-later
//
/*!
 * \file
 * \ingroup BedloadTests
 * \copydoc Dumux::ChannelBendTestProblemShallowWater
 */
#ifndef DUMUX_CHANNEL_BEND_TEST_PROBLEM_SHALLOWWATER_HH
#define DUMUX_CHANNEL_BEND_TEST_PROBLEM_SHALLOWWATER_HH

#include "spatialparams_shallowwater.hh"
#include <dumux/common/parameters.hh>

#include <dumux/freeflow/shallowwater/problem.hh>
#include <dumux/flux/shallowwater/riemannproblem.hh>
#include <dumux/freeflow/shallowwater/boundaryfluxes.hh>

namespace Dumux {

template <class TypeTag>
class ChannelBendTestProblemShallowWater;

/*!
 * \ingroup BedloadTests
 * \brief The problem class for the channel bend test (shallow water part)
 *
 * This test is based on run number four of the experiments presented in
 * Yen and Lee (1995) "Bed topography and sediment sorting in channel bend
 * with unsteady flow", Journal of Hydraulic Engineering.
 */
template <class TypeTag>
class ChannelBendTestProblemShallowWater : public ShallowWaterProblem<TypeTag>
{
    using ParentType = ShallowWaterProblem<TypeTag>;
    using PrimaryVariables = GetPropType<TypeTag, Properties::PrimaryVariables>;
    using NumEqVector = Dumux::NumEqVector<PrimaryVariables>;
    using BoundaryTypes = Dumux::BoundaryTypes<GetPropType<TypeTag, Properties::ModelTraits>::numEq()>;
    using Scalar = GetPropType<TypeTag, Properties::Scalar>;
    using ModelTraits = GetPropType<TypeTag, Properties::ModelTraits>;
    using Indices = typename ModelTraits::Indices;
    using GridGeometry = GetPropType<TypeTag, Properties::GridGeometry>;
    using NeumannFluxes = NumEqVector;
    using GridVariables = GetPropType<TypeTag, Properties::GridVariables>;
    using ElementFluxVariablesCache = typename GridVariables::GridFluxVariablesCache::LocalView;
    using ElementVolumeVariables = typename GridVariables::GridVolumeVariables::LocalView;
    using VolumeVariables = typename ElementVolumeVariables::VolumeVariables;
    using FVElementGeometry = typename GridGeometry::LocalView;
    using SubControlVolumeFace = typename FVElementGeometry::SubControlVolumeFace;
    using GridView = typename GridGeometry::GridView;
    using Element = typename GridView::template Codim<0>::Entity;
    using GlobalPosition = typename Element::Geometry::GlobalCoordinate;
    using SubControlVolume = typename FVElementGeometry::SubControlVolume;
    using SolutionVector = GetPropType<TypeTag, Properties::SolutionVector>;

public:
    ChannelBendTestProblemShallowWater(std::shared_ptr<const GridGeometry> gridGeometry,
                                       std::shared_ptr<GetPropType<TypeTag, Properties::SpatialParams>> spatialParams,
                                       std::vector<Scalar>& initialWaterDepth,
                                       std::vector<Scalar>& initialVelocityX,
                                       std::vector<Scalar>& initialVelocityY)
    : ParentType(gridGeometry, spatialParams)
    {
        name_ = getParam<std::string>("Problem.Name");

        initialWaterDepth_ = initialWaterDepth;
        initialVelocityX_ = initialVelocityX;
        initialVelocityY_ = initialVelocityY;

        flowRateInflow_ = initialFlowRateInflow_;
        freeSurfaceOutflow_ = initialFreeSurfaceOutflow_;
     }

    /*!
     * \name Problem parameters
     */
    // \{

    /*!
     * \brief The problem name
     *
     * This is used as a prefix for files generated by the simulation.
     */
    const std::string& name() const
    {
        return name_;
    }

     /*!
     * \brief Compute the source term due to bottom friction
     *
     * \param element The finite element
     * \param fvGeometry The finite-volume geometry
     * \param elemVolVars All volume variables for the element
     * \param scv The sub control volume
     *
     */
     NumEqVector source(const Element& element,
                        const FVElementGeometry& fvGeometry,
                        const ElementVolumeVariables& elemVolVars,
                        const SubControlVolume &scv) const
    {
        NumEqVector bottomFrictionSource(0.0);

        const auto& volVars = elemVolVars[scv];
        Dune::FieldVector<Scalar, 2> bottomShearStress = this->spatialParams().frictionLaw(element, scv).bottomShearStress(volVars);

        bottomFrictionSource[0] = 0.0;
        bottomFrictionSource[1] = -bottomShearStress[0] / volVars.density();
        bottomFrictionSource[2] = -bottomShearStress[1] / volVars.density();

        return bottomFrictionSource;
    }

    // \}

    /*!
     * \brief Update boundary conditions.
     *
     * \param time time [s]
     */
    void updateBoundaryConditions(const Scalar time)
    {
        // define the boundary values
        std::vector<Scalar> t{0.0,  6000.0, 18000.0};  // time [s]
        std::vector<Scalar> q{initialFlowRateInflow_, -0.053, initialFlowRateInflow_ };  // discharge [m^2/s]
        std::vector<Scalar> fs{initialFreeSurfaceOutflow_, 10.032, initialFreeSurfaceOutflow_};  // free surface [m]

        // use linear interpolation to calculate the discharge and free surface at the current time level.
        if (time < t[1]){
            flowRateInflow_ = q[0] + (q[1] - q[0]) * (time - t[0]) / (t[1] - t[0]);
            freeSurfaceOutflow_ = fs[0] + (fs[1] - fs[0]) * (time - t[0]) / (t[1] - t[0]);
        }
        else if (time < t[2]){
            flowRateInflow_ = q[1] + (q[2] - q[1]) * (time - t[1]) / (t[2] - t[1]);
            freeSurfaceOutflow_ = fs[1] + (fs[2] - fs[1]) * (time - t[1]) / (t[2] - t[1]);
        }
        else {
            flowRateInflow_ = q[2];
            freeSurfaceOutflow_ = fs[2];
        }
    }
    /*!
     * \name Boundary conditions
     */
    // \{

    /*!
     * \brief Specifies which kind of boundary condition should be
     *        used for which equation on a given boundary segment.
     *
     * \param globalPos The position for which the boundary type is set
     */
    BoundaryTypes boundaryTypesAtPos(const GlobalPosition &globalPos) const
    {
        BoundaryTypes bcTypes;
        bcTypes.setAllNeumann();
        return bcTypes;
    }

    /*!
     * \brief Specifies the Neumann boundary
     *
     * Specify the Neumann boundary for the shallow water flux.
     *
     * For the shallow water flux we need the Riemann invariants to compute the values depending
     * of the boundary type. Since we use a weak imposition we do not have a Dirichlet value.
     * We impose fluxes based on q, h, etc. computed with the Riemann invariants.
     *
     * \param element The finite element
     * \param fvGeometry The finite-volume geometry
     * \param elemVolVars All volume variables for the element
     * \param scvf The sub control volume face
     */
    NeumannFluxes neumann(const Element& element,
                          const FVElementGeometry& fvGeometry,
                          const ElementVolumeVariables& elemVolVars,
                          const ElementFluxVariablesCache& elemFluxVarsCache,
                          const SubControlVolumeFace& scvf) const
    {
        NeumannFluxes values(0.0);

        const auto& insideScv = fvGeometry.scv(scvf.insideScvIdx());
        const auto& insideVolVars = elemVolVars[insideScv];
        const auto& nxy = scvf.unitOuterNormal();
        const auto gravity = this->spatialParams().gravity(scvf.center());

        // no-flow boundary
        std::array<Scalar, 3> boundaryStateVariables = {0.0};
        auto vNormalGhost = -(nxy[0] * insideVolVars.velocity(0) +  nxy[1] * insideVolVars.velocity(1));
        auto vTangentialGhost = -nxy[1] * insideVolVars.velocity(0) + nxy[0] * insideVolVars.velocity(1);
        // re-rotate to the ghost
        boundaryStateVariables[0] = insideVolVars.waterDepth();
        boundaryStateVariables[1] = nxy[0] * vNormalGhost - nxy[1] * vTangentialGhost;
        boundaryStateVariables[2] = nxy[1] * vNormalGhost + nxy[0] * vTangentialGhost;

        // discharge boundary
        if (scvf.center()[1] < yMin_ + eps_ && scvf.center()[0] < xCenter_)
        {
            boundaryStateVariables = ShallowWater::fixedDischargeBoundary(flowRateInflow_,
                                                                          insideVolVars.waterDepth(),
                                                                          insideVolVars.velocity(0),
                                                                          insideVolVars.velocity(1),
                                                                          gravity,
                                                                          nxy);
        }
        // free surface boundary
        else if (scvf.center()[1] < yMin_ + eps_ && scvf.center()[0] > xCenter_)
        {
            boundaryStateVariables =  ShallowWater::fixedWaterDepthBoundary(freeSurfaceOutflow_ - insideVolVars.bedSurface(),
                                                                            insideVolVars.waterDepth(),
                                                                            insideVolVars.velocity(0),
                                                                            insideVolVars.velocity(1),
                                                                            gravity,
                                                                            nxy);
        }

        auto riemannFlux = ShallowWater::riemannProblem(insideVolVars.waterDepth(),
                                                        boundaryStateVariables[0],
                                                        insideVolVars.velocity(0),
                                                        boundaryStateVariables[1],
                                                        insideVolVars.velocity(1),
                                                        boundaryStateVariables[2],
                                                        insideVolVars.bedSurface(),
                                                        insideVolVars.bedSurface(),
                                                        gravity,
                                                        nxy);

        values[Indices::massBalanceIdx] = riemannFlux[0];
        values[Indices::velocityXIdx]   = riemannFlux[1];
        values[Indices::velocityYIdx]   = riemannFlux[2];

        return values;
    }

    /*!
     * \brief Get coupled variables
     *
     * Get h, u, v and the bottom shear stress to exchange them with the bedload model.
     *
     * \param curSol The current solution
     * \param gridVariables The grid variables
     */
    template<class SolutionVector, class GridVariables>
    std::map<std::string, std::vector<Scalar>> getCoupledVariables(const SolutionVector& curSol,
                                                                   const GridVariables& gridVariables)
    {
        int size = this->gridGeometry().gridView().size(0);
        // make map with a string and a vector to store the variable names and their values
        std::map<std::string, std::vector<Scalar>> coupledVariables;
        // add the variable names
        coupledVariables["h"] = std::vector<Scalar>(size, 0.0);
        coupledVariables["u"] = std::vector<Scalar>(size, 0.0);
        coupledVariables["v"] = std::vector<Scalar>(size, 0.0);
        coupledVariables["bottomShearStressX"] = std::vector<Scalar>(size, 0.0);
        coupledVariables["bottomShearStressY"] = std::vector<Scalar>(size, 0.0);
        // add the values
        for (const auto& element : elements(this->gridGeometry().gridView()))
        {
            auto fvGeometry = localView(this->gridGeometry());
            fvGeometry.bindElement(element);

            auto elemVolVars = localView(gridVariables.curGridVolVars());
            elemVolVars.bindElement(element, fvGeometry, curSol);

            // get local index of the element
            const auto eIdx = this->gridGeometry().elementMapper().index(element);
            // we loop over the ghost entities, too
            for (auto&& scv : scvs(fvGeometry))
            {
                coupledVariables["h"][eIdx] = elemVolVars[scv].waterDepth();
                coupledVariables["u"][eIdx] = elemVolVars[scv].velocity(0);
                coupledVariables["v"][eIdx] = elemVolVars[scv].velocity(1);
                auto bottomShearStress = this->spatialParams().frictionLaw(element, scv).bottomShearStress(elemVolVars[scv]);
                coupledVariables["bottomShearStressX"][eIdx] = bottomShearStress[0];
                coupledVariables["bottomShearStressY"][eIdx] = bottomShearStress[1];
            }
        }
        return coupledVariables;
    }
    // \}

    /*!
     * \name Volume terms
     */
    // \{

    /*!
     * \brief Evaluate the initial values for a control volume.
     *
     * For this method, the \a values parameter stores primary variables.
     *
     * \param element The finite element
     */
    PrimaryVariables initial(const Element& element) const
    {
        PrimaryVariables values(0.0);
        auto elemId = this->gridGeometry().elementMapper().index(element);

        values[0] = initialWaterDepth_[elemId];
        values[1] = initialVelocityX_[elemId];
        values[2] = initialVelocityY_[elemId];

        return values;
    }

    // \}

private:
    static constexpr Scalar eps_ = 1.0e-4;     // [-]
    Scalar flowRateInflow_;                    // [m^2/s]
    Scalar freeSurfaceOutflow_;                // [m]
    Scalar initialFlowRateInflow_ = -0.02;     // [m^2/s]
    Scalar initialFreeSurfaceOutflow_ = 9.983; // [m]
    std::vector<Scalar> initialWaterDepth_;    // [m]
    std::vector<Scalar> initialVelocityX_;     // [m/s]
    std::vector<Scalar> initialVelocityY_;     // [m/s]
    std::string name_;
    Scalar xCenter_ = 101.1819;                // [m]
    Scalar yMin_ = 31.1371;                    // [m]
};

} //end namespace Dumux

#endif
