// -*- mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
// vi: set et ts=4 sw=4 sts=4:
//
// SPDX-FileCopyrightText: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
// SPDX-License-Identifier: GPL-3.0-or-later
//
/*!
 * \file
 * \ingroup Core
 * \brief Base class for all standard finite volume or finite element problems
 */
#ifndef DUMUX_COMMON_DEFAULT_PROBLEM_HH
#define DUMUX_COMMON_DEFAULT_PROBLEM_HH

#include <memory>

#include <dumux/common/properties.hh>
#include <dumux/common/parameters.hh>
#include <dumux/common/boundarytypes_.hh>
#include <dumux/common/numeqvector.hh>

#include <dumux/assembly/boundaryfluxintegral.hh>
#include <dumux/discretization/concepts.hh>
#include <dumux/common/pointsources.hh>

namespace Dumux::Experimental {

/*!
 * \ingroup Core
 * \brief Base class for all standard finite volume or finite element problems
 *
 * \note All quantities (regarding the units) are specified assuming a
 *       three-dimensional world. Problems discretized using 2D grids
 *       are assumed to be extruded by \f$1 m\f$ and 1D grids are assumed
 *       to have a cross section of \f$1m \times 1m\f$.
 */
template<class TypeTag>
class Problem
{
    using Implementation = GetPropType<TypeTag, Properties::Problem>;

    using GridDiscretization = GetPropType<TypeTag, Properties::GridGeometry>;
    using ElementDiscretization = typename GridDiscretization::LocalView;
    using GridView = typename GridDiscretization::GridView;
    using Element = typename GridView::template Codim<0>::Entity;
    using GlobalPosition = typename Element::Geometry::GlobalCoordinate;

    using Scalar = GetPropType<TypeTag, Properties::Scalar>;
    using PrimaryVariables = GetPropType<TypeTag, Properties::PrimaryVariables>;
    using NumEqVector = Dumux::NumEqVector<GetPropType<TypeTag, Properties::PrimaryVariables>>;
    using BoundaryTypes = Dumux::Experimental::BoundaryTypes<PrimaryVariables::size()>;

public:
    //! export traits of this problem
    struct Traits
    {
        using Scalar = Problem::Scalar;
        using PrimaryVariables = Problem::PrimaryVariables;
        using NumEqVector = Problem::NumEqVector;
    };

    /*!
     * \brief Constructor
     * \param gridDiscretization The grid discretization
     * \param paramGroup The parameter group in which to look for runtime parameters first (default is "")
     */
    Problem(std::shared_ptr<const GridDiscretization> gridDiscretization, const std::string& paramGroup = "")
    : gridDiscretization_(gridDiscretization)
    , paramGroup_(paramGroup)
    {
        // set a default name for the problem
        problemName_ = getParamFromGroup<std::string>(paramGroup, "Problem.Name", "sim");
    }

    /*!
     * \brief The problem name.
     *
     * This is used as a prefix for files generated by the simulation.
     * It could be either overwritten by the problem files, or simply
     * declared over the setName() function in the application file.
     */
    const std::string& name() const
    {
        return problemName_;
    }

    /*!
     * \brief Set the problem name.
     *
     * \param newName The problem's name
     */
    void setName(const std::string& newName)
    {
        problemName_ = newName;
    }

    /*!
     * \name Boundary conditions and sources defining the problem
     */
    // \{

    /*!
     * \brief Specifies which kind of boundary condition should be
     *        used for which equation on a given boundary face.
     *
     * \param elemDisc The element discretization
     * \param boundaryFace The boundary face
     */
    BoundaryTypes boundaryTypes(const ElementDiscretization& elemDisc,
                                const typename ElementDiscretization::BoundaryFace& boundaryFace) const
    {
        // forward it to the method which only takes the global coordinate
        return asImp_().boundaryTypesAtPos(boundaryFace.center());
    }

    /*!
     * \brief Specifies which kind of boundary condition should be
     *        used for which equation on a given boundary segment.
     *
     * \param globalPos The position in global coordinates
     */
    BoundaryTypes boundaryTypesAtPos(const GlobalPosition &globalPos) const
    {
        //! As a default, i.e. if the user's problem does not overload any boundaryTypes method
        //! we set no-flux everywhere.
        return BoundaryTypes{};
    }

    /*!
     * \brief Evaluates finite-element boundary flux integral contributions for a given boundary face.
     *
     * \param residual The residual vector to which the boundary flux contributions are added
     * \param elemDisc The element discretization
     * \param elemVars All variables for the element
     * \param boundaryFace The boundary face for which the boundary flux integral is evaluated
     * \param bcTypes The boundary types
     */
    template<class ResidualVector, class ElementVariables, class BoundaryTypes>
    void addFEBoundaryFluxIntegral(ResidualVector& residual,
                                   const ElementDiscretization& elemDisc,
                                   const ElementVariables& elemVars,
                                   const typename ElementDiscretization::BoundaryFace& boundaryFace,
                                   const BoundaryTypes& bcTypes) const
    {
        if constexpr (Concepts::HybridElementDiscretization<ElementDiscretization>
                   || Concepts::FEElementDiscretization<ElementDiscretization>)
            Dumux::Experimental::addFEBoundaryFluxIntegral(residual, asImp_(), elemDisc, elemVars, boundaryFace, bcTypes);
    }

    /*!
     * \brief Evaluates finite-volume boundary flux integral contributions for a given scvf.
     *
     * \param residual The residual vector to which the boundary flux contributions are added
     * \param elemDisc The element discretization
     * \param elemVars All variables for the element
     * \param scvf The scvf for which the boundary flux integral is evaluated
     * \param bcTypes The boundary types
     */
    template<class ResidualVector, class ElementVariables, class BoundaryTypes>
    void addFVBoundaryFluxIntegral(ResidualVector& residual,
                                   const ElementDiscretization& elemDisc,
                                   const ElementVariables& elemVars,
                                   const typename ElementDiscretization::SubControlVolumeFace& scvf,
                                   const BoundaryTypes& bcTypes) const
    {
        if constexpr (Concepts::FVElementDiscretization<ElementDiscretization>)
            Dumux::Experimental::addFVBoundaryFluxIntegral(residual, asImp_(), elemDisc, elemVars, scvf, bcTypes);
    }


    /*!
     * \brief Evaluate the boundary conditions for a neumann
     *        boundary segment.
     *
     * This is the method for the case where the Neumann condition is
     * potentially solution dependent
     *
     * \param elemDisc The element discretization
     * \param elemVars All variables for the element
     * \param faceIpData Face interpolation point data
     *
     * Negative values mean influx.
     * E.g. for the mass balance that would be the mass flux in \f$ [ kg / (m^2 \cdot s)] \f$.
     */
    template<class ElementVariables, class FaceIpData>
    NumEqVector boundaryFlux(const ElementDiscretization& elemDisc,
                             const ElementVariables& elemVars,
                             const FaceIpData& faceIpData) const
    {
        // forward it to the interface with only the global position
        return asImp_().boundaryFluxAtPos(faceIpData.global());
    }

    /*!
     * \brief Evaluate the boundary flux at a given position.
     *
     * \param globalPos The position of the boundary face's integration point in global coordinates
     *
     * Negative values mean influx.
     * E.g. for the mass balance that would be the mass flux in \f$ [ kg / (m^2 \cdot s)] \f$.
     */
    NumEqVector boundaryFluxAtPos(const GlobalPosition& globalPos) const
    {
        //! As a default, i.e. if the user's problem does not overload any boundary flux method
        //! return no-flux boundary conditions at all boundaries
        return NumEqVector(0.0);
    }

    /*!
     * \brief Evaluate the source term at a given interpolation point
     *
     * This is the method for the case where the source term is
     * potentially solution dependent and requires some quantities that
     * are specific to the fully-implicit method.
     *
     * \param elemDisc The element discretization
     * \param elemVars All variables for the element
     * \param ipData Interpolation point data
     *
     * For this method, the return parameter stores the conserved quantity rate
     * generated or annihilate per volume unit. Positive values mean
     * that the conserved quantity is created, negative ones mean that it vanishes.
     */
    template<class ElementVariables, class IpData>
    NumEqVector source(const ElementDiscretization& elemDisc,
                       const ElementVariables& elemVars,
                       const IpData& ipData) const
    {
        return asImp_().sourceAtPos(ipData.global());
    }

    /*!
     * \brief Evaluate the source term for all phases at a given position
     *
     * \param globalPos The position in global coordinates
     *
     * For this method, the values parameter stores the conserved quantity rate
     * generated or annihilate per volume unit. Positive values mean
     * that the conserved quantity is created, negative ones mean that it vanishes.
     * E.g. for the mass balance that would be a mass rate in \f$ [ kg / (m^3 \cdot s)] \f$.
     */
    NumEqVector sourceAtPos(const GlobalPosition &globalPos) const
    {
        //! As a default, i.e. if the user's problem does not overload any source method
        //! return 0.0 (no source terms)
        return NumEqVector(0.0);
    }

    /*!
     * \brief Add source term derivative to the Jacobian
     * \note Only needed in case of analytic differentiation and solution dependent sources
     */
    template<class MatrixBlock, class Variables, class IpData>
    void addSourceDerivatives(MatrixBlock& block,
                              const Element& element,
                              const ElementDiscretization& elemDisc,
                              const Variables& volVars,
                              const IpData& ipData) const {}

    /*!
     * \brief Return the point sources for this problem.
     *
     * By default, no point sources are present (returns `EmptyPointSources` for which
     * `empty()` returns `true`). Derived classes can overwrite this function
     * to return a `PointSources` object containing point sources with contexts and an evaluation function.
     *
     * The returned object must provide the following interface:
     *
     * - `bool empty() const`
     *   Returns `true` if no point sources are registered; otherwise `false`.
     *
     * - For **finite-volume** schemes:
     *   \code
     *   auto contexts(const ElementDiscretization& elemDisc,
     *                 const SubControlVolume& scv) const;
     *   \endcode
     *   Returns a range of `contexts` related to the `scv`.
     *
     * - For **finite-element** schemes:
     *   \code
     *   auto contexts(const ElementDiscretization& elemDisc,
     *                 const Element& element) const;
     *   \endcode
     *   Returns a range of `contexts` related to the `element`.
     *
     * - `auto eval(const ElementDiscretization& elemDisc,
     *              const ElementVariables& elemVars,
     *              const Context& context) const`
     *   Evaluates the point source for the given context.
     */
    EmptyPointSources pointSources() const
    { return {}; }

    //! The grid discretization
    [[deprecated("Use gridDiscretization() instead")]]
    const GridDiscretization& gridGeometry() const
    { return *gridDiscretization_; }

    //! The grid discretization
    const GridDiscretization& gridDiscretization() const
    { return *gridDiscretization_; }

    //! The parameter group in which to retrieve runtime parameters
    const std::string& paramGroup() const
    { return paramGroup_; }

protected:
    //! Returns the implementation of the problem (i.e. static polymorphism)
    Implementation &asImp_()
    { return *static_cast<Implementation *>(this); }

    //! \copydoc asImp_()
    const Implementation &asImp_() const
    { return *static_cast<const Implementation *>(this); }

private:
    //! The grid discretization
    std::shared_ptr<const GridDiscretization> gridDiscretization_;

    //! The parameter group in which to retrieve runtime parameters
    std::string paramGroup_;

    //! The name of the problem
    std::string problemName_;
};

} // end namespace Dumux::Experimental

#endif
