# SPDX-FileCopyrightInfo: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
# SPDX-License-Identifier: GPL-3.0-or-later

@startuml
scale 0.8
top to bottom direction
hide empty members
set separator none
skinparam lineType ortho
skinparam nodesep 30
skinparam ranksep 30

package "User Scenario" {
        class Problem{}
        class SpatialParams [[./../html/group___spatial_parameters.html]]{}
        file params as "
            params.input
            ----
            <code>
            [TimeLoop]
            DtInitial = 250 # [s]
            ...
            </code>
        "
        file main as "
            main.cc
            ----
            <code>
            int main(int argc, char** argv)
            {
                ...
                using TypeTag = Properties::TTag::...;
                ...
                using Problem = GetPropType<TypeTag, Properties::Problem>;
                auto problem = std::make_shared<Problem>(gridGeometry);
                ...
            }
            </code>
        "
    package "Properties"  [[./../html/group___properties.html]] {
        package "TTag" {
            struct MyTypeTag{}
        }
    }
}
package "Dune" {
    package "dune-istl" {
class "ISTL solvers"
class "ISTL matrices"
class "ISTL vectors"
}
    package "dune-grid" {
class "YaspGrid"
}
package "dune-common" {
class "ParameterTree" {}
}
}
package "DuMux" {
    package "Grid" {
       interface GridManager{}
       interface GridView{}
       class GridGeometry{}
    }
    package "Variables" {
       class GridVariables{}
       class PrimaryVariables{}
       class SolutionVector{}
    }
    package "Assembly" [[./../html/group___assembly.html]] {
        class Assembler{}
        class LocalAssembler{}
        class LocalResidual{}

    }
    package "Solving" {
        class PDESolver [[./../html/group___nonlinear.html]] {}
        interface LinearSolver [[./../html/group___linear.html]] {}
        class TimeLoop{}
    }
    package "Output" {
        class IOField{}
        class VTKOutputModule
    }
}

"Dune" -[hidden]u------ "DuMux"
"DuMux" -[hidden]u----"User Scenario"
"DuMux" -[hidden]u----- "User Scenario"
"dune-grid" -[hidden]r---- "dune-istl"
"ISTL solvers" -[hidden]r---- "ISTL matrices"
"ISTL matrices" -[hidden]r---- "ISTL vectors"
"ISTL vectors" -[hidden]r---- "ParameterTree"
"YaspGrid" -[hidden]r---- "ISTL matrices"
"Output" -[hidden]r---- "Solving"
"Solving" -[hidden]r---- "Assembly"
"Assembly" -[hidden]r---- "Variables"
"Assembly" -[hidden]r---- "Variables"
"Variables" -[hidden]r---- "Grid"
"Variables" -[hidden]d---- "ISTL vectors"
LinearSolver <-d- "ISTL solvers"
Assembler <-d- "ISTL matrices"
LinearSolver <-d- "ISTL vectors"
 "dune-grid" -u--> GridManager
GridManager o-u- GridView
GridView -u-> GridGeometry
GridGeometry -u-> Problem
GridGeometry -u-> SpatialParams
GridGeometry --> GridVariables
GridGeometry -l-> Assembler
LinearSolver -d-> PDESolver
LocalResidual -d- LocalAssembler
LocalResidual ---o Assembler
LocalAssembler -d-o Assembler
GridVariables -l-> VTKOutputModule
GridVariables --- SolutionVector
PrimaryVariables -d-o SolutionVector
IOField --> VTKOutputModule
VTKOutputModule <-- SolutionVector
Assembler --> PDESolver
PDESolver <-- TimeLoop
TimeLoop --> Assembler
Problem --> Assembler
SolutionVector --> Assembler
GridVariables --> Assembler
SpatialParams -r-> Problem
main -l- Properties
"Output" -[hidden]r- "Solving"
"Solving" -[hidden]r- "Assembly"
"Assembly" -[hidden]r- "Variables"
"Variables" -[hidden]r- "Grid"
Properties -[#red,hidden]- GridGeometry
Properties -[#red,hidden]d- GridVariables
Properties -[#red,hidden]r- PrimaryVariables
Properties -[#red,hidden]- SolutionVector
Properties -[#red,hidden]- Assembler
Properties -[#red,hidden]- LocalAssembler
Properties -[#red,hidden]- LocalResidual
Properties -[#red,hidden]- PDESolver
Properties -[#red,hidden]- TimeLoop
Properties -[#red,hidden]- IOField
Properties -[#red,hidden]- VTKOutputModule
Properties -[#red,hidden]- SpatialParams
Properties -[#red,hidden] Problem
"DuMux" -[#red]- Properties
"Dune" -[#red]- Properties
params -[hidden]d- "Output"



@enduml
