@startuml
scale 0.8
top to bottom direction
hide empty members
set separator none
allowmixing

package "Dune" {
    package "dune-istl"{
class "ISTL solvers"
class "ISTL matrices"
class "ISTL vectors"
}
    package dune-grid{
class YaspGrid
}
}

package "DuMux" {
    package "Grid" {
       interface GridManager{}
       interface GridView{}
       class GridGeometry{}
    }
    package "Variables" {
       class GridVariables{}
       class PrimaryVariables{}
       class SolutionVector{}
    }
    package "Assembly" [[./../html/group___assembly.html]] {
        class Assembler{}
        class LocalAssembler{}
        class LocalResidual{}
        
    }
    package "Solving" {
        class PDESolver [[./../html/group___nonlinear.html]] {}
        interface LinearSolver [[./../html/group___linear.html]] {}
        class TimeLoop{}
    }
    package "Output" {
        class IOField{}
        class VTKOutputModule
    }
}

package "User Scenario" {
        class Problem{}
        class SpatialParams{}
        file params as "
            params.input
            ----
            <code>
            [TimeLoop]
            DtInitial = 250 # [s]
            ...
            </code>
        "
        file main as "
            main.cc
            ----
            <code>
            int main(int argc, char** argv)
            {
                ...
                using TypeTag = Properties::TTag::...;
                ...
                using Problem = GetPropType<TypeTag, Properties::Problem>;
                auto problem = std::make_shared<Problem>(gridGeometry);
                ...
            }
            </code>
        "
    package "Properties" {
        package "TTag" {
            struct MyTypeTag{}
        }
        struct "Problem<MyTypeTag>"{}
        struct "SpatialParams<MyTypeTag>"{}
    }
}


LinearSolver <-- "dune-istl"
GridManager <-- "dune-grid"
GridManager o-- GridView
GridView --o GridGeometry
GridGeometry --o Problem
GridGeometry --o SpatialParams
GridGeometry --o GridVariables
GridGeometry --o Assembler
LinearSolver --> PDESolver
LocalResidual --o LocalAssembler
LocalAssembler <-- Assembler: uses
GridVariables --> VTKOutputModule
PrimaryVariables --o SolutionVector
IOField --> VTKOutputModule
Assembler --> PDESolver
PDESolver --> TimeLoop
SolutionVector --> Assembler
GridVariables --> Assembler
SpatialParams --o Problem
"Problem<MyTypeTag>" -- Problem
"SpatialParams<MyTypeTag>" -- SpatialParams
main -- Properties
@enduml
