#./noflowdomain_2p2cni_ld -Grid.File "./grids/singlefracturequadrilateral0.msh" -Problem.Name "noflow_2p2cni_ld_refinement0"
#./noflowdomain_2p2cni_ld -Grid.File "./grids/singlefracturequadrilateral1.msh" -Problem.Name "noflow_2p2cni_ld_refinement1"
./noflowdomain_2p2cni_ld -Grid.File "./grids/singlefracturequadrilateral2.msh" -Problem.Name "noflow_2p2cni_ld_refinement2"
#./noflowdomain_2p2cni_ld -Grid.File "./grids/singlefracturequadrilateral3.msh" -Problem.Name "noflow_2p2cni_ld_refinement3"
#./noflowdomain_2p2cni_ld -Grid.File "./grids/singlefracturequadrilateral4.msh" -Problem.Name "noflow_2p2cni_ld_refinement4"
#./noflowdomain_2p2cni_ld -Grid.File "./grids/singlefracturequadrilateral5.msh" -Problem.Name "noflow_2p2cni_ld_refinement5"
#./noflowdomain_2p2cni_ld -Grid.File "./grids/singlefracturequadrilateral6.msh" -Problem.Name "noflow_2p2cni_ld_refinement6"
