# additional macros
include(AddGstatFileLinks)
include(AddInputFileLinks)
include(DumuxDoxygen)
include(DumuxTestMacros)

find_package(GLPK)
find_package(Gnuplot)
set(HAVE_GNUPLOT ${GNUPLOT_FOUND})
find_package(Gstat)
find_package(Gmsh)
find_package(NLOPT)
find_package(PTScotch)
find_package(PVPython)
find_package(Valgrind)
find_package(Trilinos)
set(HAVE_TRILINOS ${Trilinos_FOUND})
if(Trilinos_FOUND)
  dune_register_package_flags(LIBRARIES ${Trilinos_LIBRARIES} ${MPI_CXX_LIBRARIES})
  include_directories(${Trilinos_INCLUDE_DIRS})
endif()
