#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
# SPDX-License-Identifier: GPL-3.0-or-later

import argparse
import json
import pathlib
import sys

# fixed assignment order for colors (JSON object keys are alphabetical, which would otherwise
# put explicit and implicit Euler next to each other in the tab10 cycle and give them similar
# reddish/brownish colors that are hard to tell apart)
METHOD_ORDER = ["explicit_euler", "implicit_euler", "crank_nicolson", "heun",
                "dirk2", "qin_zhang", "rk3", "dirk3", "rk4"]


def split_attribution(name: str):
    """Split a trailing parenthetical attribution (e.g. "(Alexander)") onto its own line."""
    if name.endswith(")"):
        idx = name.rfind(" (")
        if idx != -1:
            return name[:idx], name[idx + 1:]
    return name, None


def format_label(name: str) -> str:
    """Format a method name as a label, moving a trailing attribution to a second line."""
    main, attribution = split_attribution(name)
    return f"{main}\n{attribution}" if attribution else main


def style_axes(ax, title, limit):
    ax.axhline(0.0, color="0.7", linewidth=0.8)
    ax.axvline(0.0, color="0.7", linewidth=0.8)
    ax.set_title(title)
    ax.set_xlabel("Re(z)")
    ax.set_ylabel("Im(z)")
    ax.set_xlim(-limit, limit)
    ax.set_ylim(-limit, limit)
    ax.set_aspect("equal", adjustable="box")


def plot_methods(plt, method_ids, methods, limit, title, colors):
    # one row, one panel per method plus an overlay panel
    n = len(method_ids) + (1 if len(method_ids) > 1 else 0)
    fig, axes = plt.subplots(1, n, figsize=(4.3 * n, 4.6), constrained_layout=True)
    axes = axes.flat if hasattr(axes, "flat") else [axes]

    offset = 0
    if len(method_ids) > 1:
        ax = axes[0]
        for method_id in method_ids:
            color = colors[method_id]
            method = methods[method_id]
            boundary = method.get("boundaryPoints", [])
            if boundary:
                x = [p[0] for p in boundary] + [boundary[0][0]]
                y = [p[1] for p in boundary] + [boundary[0][1]]
                ax.fill(x, y, color=color, alpha=0.25)
                ax.plot(x, y, color=color, linewidth=1.2, label=format_label(method.get("name", method_id)))
            else:
                points = method.get("stablePoints", [])
                x = [p[0] for p in points]
                y = [p[1] for p in points]
                ax.scatter(x, y, s=4, color=color, alpha=0.25, label=format_label(method.get("name", method_id)))

        style_axes(ax, f"{title} (overlay)", limit)
        ax.legend(loc="upper left")
        offset = 1

    for idx, method_id in enumerate(method_ids):
        ax = axes[idx + offset]
        color = colors[method_id]
        method = methods[method_id]

        boundary = method.get("boundaryPoints", [])
        if boundary:
            x = [p[0] for p in boundary] + [boundary[0][0]]
            y = [p[1] for p in boundary] + [boundary[0][1]]
            ax.fill(x, y, color=color, alpha=0.3)
            ax.plot(x, y, color=color, linewidth=1.0)

        points = method.get("stablePoints", [])
        if points:
            x = [p[0] for p in points]
            y = [p[1] for p in points]
            ax.scatter(x, y, s=4, color=color)

        style_axes(ax, format_label(method.get("name", method_id)), limit)

    return fig


def plot_comparison(plt, method_ids, methods, limit, colors):
    fig, axes = plt.subplots(1, len(method_ids), figsize=(4.3 * len(method_ids), 4.6), constrained_layout=True)
    axes = axes.flat if hasattr(axes, "flat") else [axes]

    for ax, method_id in zip(axes, method_ids):
        method = methods[method_id]
        color = colors[method_id]

        numerical = method.get("boundaryPoints", [])
        if numerical:
            x = [p[0] for p in numerical] + [numerical[0][0]]
            y = [p[1] for p in numerical] + [numerical[0][1]]
            ax.plot(x, y, color=color, linewidth=1.5, label="numerical")

        analytical = method.get("boundaryPointsAnalytical", [])
        if analytical:
            step = max(1, len(analytical) // 30)
            x = [p[0] for p in analytical[::step]]
            y = [p[1] for p in analytical[::step]]
            ax.plot(x, y, "x", color="k", markersize=6, label="analytical")

        style_axes(ax, format_label(method.get("name", method_id)), limit)
        ax.legend(loc="upper left")

    return fig


def main() -> int:
    parser = argparse.ArgumentParser(description="Plot sampled RK stability regions from JSON data.")
    parser.add_argument("--input", required=True, help="Input JSON file generated by the C++ test")
    parser.add_argument("--output", required=True, help="Output image file (e.g. png)")
    args = parser.parse_args()

    input_path = pathlib.Path(args.input)
    output_path = pathlib.Path(args.output)

    if not input_path.exists():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 1

    with input_path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not found; skipping plot generation.")
        return 0

    plt.rcParams.update({
        "font.size": 12,
        "axes.titlesize": 13,
        "axes.labelsize": 12,
        "legend.fontsize": 11,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
    })

    methods = data["methods"]
    limit = data.get("limit", 4.0)
    method_ids = list(methods.keys())
    explicit_ids = [m for m in method_ids if methods[m].get("boundaryPoints")]
    implicit_ids = [m for m in method_ids if m not in explicit_ids]

    ordered_ids = [m for m in METHOD_ORDER if m in methods]

    cmap = plt.get_cmap("tab10").colors
    colors = {method_id: cmap[i % len(cmap)] for i, method_id in enumerate(ordered_ids)}

    output_path.parent.mkdir(parents=True, exist_ok=True)

    for group_name, group_ids in [("explicit", explicit_ids), ("implicit", implicit_ids)]:
        if not group_ids:
            continue
        fig = plot_methods(plt, group_ids, methods, limit, f"{group_name.capitalize()} methods", colors)
        group_path = output_path.with_name(f"{output_path.stem}_{group_name}{output_path.suffix}")
        fig.savefig(group_path, dpi=180)
        print(f"Wrote plot to {group_path}")

    if explicit_ids:
        fig = plot_comparison(plt, explicit_ids, methods, limit, colors)
        comparison_path = output_path.with_name(f"{output_path.stem}_comparison{output_path.suffix}")
        fig.savefig(comparison_path, dpi=180)
        print(f"Wrote plot to {comparison_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
