#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
# SPDX-License-Identifier: GPL-3.0-or-later

import argparse
import json
import pathlib
import sys

# fixed assignment order for colors, consistent with the other timestepping plots
METHOD_ORDER = ["explicit_euler", "implicit_euler", "crank_nicolson", "heun",
                "dirk2", "qin_zhang", "rk3", "dirk3", "rk4"]


def main() -> int:
    parser = argparse.ArgumentParser(description="Plot the Qin-Zhang symplecticity benchmark from JSON data.")
    parser.add_argument("--input", required=True, help="Input JSON file generated by the C++ test")
    parser.add_argument("--output", required=True, help="Output image file (e.g. png)")
    args = parser.parse_args()

    input_path = pathlib.Path(args.input)
    output_path = pathlib.Path(args.output)

    if not input_path.exists():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 1

    with input_path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not found; skipping plot generation.")
        return 0

    plt.rcParams.update({
        "font.size": 12,
        "axes.titlesize": 13,
        "axes.labelsize": 12,
        "legend.fontsize": 11,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
    })

    methods = data["methods"]
    periods = data.get("periods", "")

    ordered_ids = [m for m in METHOD_ORDER if m in methods]
    cmap = plt.get_cmap("tab10").colors
    colors = {method_id: cmap[i % len(cmap)] for i, method_id in enumerate(ordered_ids)}

    output_path.parent.mkdir(parents=True, exist_ok=True)

    fig, (ax_phase, ax_energy) = plt.subplots(1, 2, figsize=(12.0, 5.2), constrained_layout=True)

    # phase-space panel: the symplectic scheme's closed orbit against a dissipative
    # reference (implicit Euler) spiralling inward
    phase_ids = [m for m in ordered_ids if m in ("implicit_euler", "qin_zhang")]
    for method_id in phase_ids:
        method = methods[method_id]
        trajectory = method.get("trajectory", [])
        if not trajectory:
            continue
        q = [p[0] for p in trajectory]
        p = [pt[1] for pt in trajectory]
        ax_phase.plot(q, p, color=colors[method_id], linewidth=1.0, label=method.get("name", method_id))

    ax_phase.plot([1.0], [0.0], "ko", markersize=4)
    ax_phase.set_xlabel("position $q$")
    ax_phase.set_ylabel("momentum $p$")
    ax_phase.set_title(f"Phase-space trajectory ({periods} periods)")
    ax_phase.set_aspect("equal", adjustable="box")
    ax_phase.grid(True, alpha=0.3)
    ax_phase.legend(loc="upper right")

    # energy drift |E(t)/E_0 - 1| on a log axis to span the many orders of magnitude between
    # the schemes; values are clamped to a small floor so exact zeros remain plottable
    for method_id in ordered_ids:
        method = methods[method_id]
        history = method.get("energy", [])
        if not history:
            continue
        t = [e[0] for e in history]
        drift = [max(abs(e[1] - 1.0), 1e-16) for e in history]
        ax_energy.semilogy(t, drift, color=colors[method_id], linewidth=1.2, label=method.get("name", method_id))

    ax_energy.set_xlabel("time $t$")
    ax_energy.set_ylabel(r"energy drift $|E(t)/E_0 - 1|$")
    ax_energy.set_title("Energy conservation")
    ax_energy.grid(True, which="both", alpha=0.3)
    ax_energy.legend(loc="center right")

    fig.savefig(output_path, dpi=180, bbox_inches="tight")
    print(f"Wrote plot to {output_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
