#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
# SPDX-License-Identifier: GPL-3.0-or-later

import argparse
import json
import pathlib
import sys

# fixed assignment order for colors/markers (JSON object keys are alphabetical, which would
# otherwise put explicit and implicit Euler next to each other in the tab10 cycle and give
# them similar reddish/brownish colors that are hard to tell apart)
METHOD_ORDER = ["explicit_euler", "implicit_euler", "crank_nicolson", "heun",
                "dirk2", "qin_zhang", "rk3", "dirk3", "rk4"]


def split_attribution(name: str):
    """Split a trailing parenthetical attribution (e.g. "(Alexander)") onto its own line."""
    if name.endswith(")"):
        idx = name.rfind(" (")
        if idx != -1:
            return name[:idx], name[idx + 1:]
    return name, None


def format_label(name: str, suffix: str = "") -> str:
    """Format a method name as a label, moving a trailing attribution to a second line."""
    main, attribution = split_attribution(name)
    first_line = f"{main}{suffix}"
    return f"{first_line}\n{attribution}" if attribution else first_line


def add_slope_triangle(ax, x0, y0, order, width=0.35, color="0.3"):
    """Draw a right-triangle slope marker, labeling the rise with the order p and the run with 1."""
    x1 = x0 * 10**width
    y1 = y0 * 10**(order * width)
    ax.plot([x0, x1, x1, x0], [y0, y0, y1, y0], color=color, linewidth=0.8)
    ax.text(x1 * 10**0.04, (y0 * y1)**0.5, str(order), color=color,
            ha="left", va="center", fontsize=11)
    ax.text((x0 * x1)**0.5, y0 * 10**-0.12, "1", color=color,
            ha="center", va="top", fontsize=11)


def main() -> int:
    parser = argparse.ArgumentParser(description="Plot observed convergence orders from JSON data.")
    parser.add_argument("--input", required=True, help="Input JSON file generated by the C++ test")
    parser.add_argument("--output", required=True, help="Output image file (e.g. png)")
    args = parser.parse_args()

    input_path = pathlib.Path(args.input)
    output_path = pathlib.Path(args.output)

    if not input_path.exists():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 1

    with input_path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not found; skipping plot generation.")
        return 0

    plt.rcParams.update({
        "font.size": 12,
        "axes.titlesize": 13,
        "axes.labelsize": 12,
        "legend.fontsize": 11,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
    })

    methods = data["methods"]

    # all methods are evaluated at the same set of step sizes
    dts = [p[0] for p in next(iter(methods.values()))["convergence"]]

    ordered_ids = [m for m in METHOD_ORDER if m in methods]

    cmap = plt.get_cmap("tab10").colors
    colors = {method_id: cmap[i % len(cmap)] for i, method_id in enumerate(ordered_ids)}

    markers = ["o", "s", "^", "D", "v", "P", "X", "*"]
    marker_styles = {method_id: markers[i % len(markers)] for i, method_id in enumerate(ordered_ids)}

    output_path.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(8.0, 6.0))

    for method_id, method in sorted(methods.items(), key=lambda kv: kv[1]["order"]):
        errors = [p[1] for p in method["convergence"]]
        ax.loglog(dts, errors, linestyle="-", marker=marker_styles[method_id], color=colors[method_id],
                  label=format_label(method["name"], suffix=f" (p={method['order']})"))

    # reference slope lines, each anchored to a method that attains that order;
    # a slope triangle annotates the local rise (p) over run (1) directly on the line
    reference_anchors = {1: "explicit_euler", 2: "crank_nicolson", 3: "dirk3", 4: "rk4"}
    x_anchor = dts[1]
    for order, anchor_id in reference_anchors.items():
        anchor_error = methods[anchor_id]["convergence"][0][1]
        ref = lambda dt, e0=anchor_error, p=order: 0.3 * e0 * (dt / dts[0]) ** p
        ax.loglog([dts[0], dts[-1]], [ref(dts[0]), ref(dts[-1])], "k--", linewidth=1.0)
        add_slope_triangle(ax, x_anchor, ref(x_anchor), order)

    ax.set_xlabel(r"time step size $\Delta t$")
    ax.set_ylabel("absolute error at $t=1$")
    ax.set_title("Observed order of temporal convergence")
    ax.grid(True, which="both", alpha=0.3)
    ax.legend(loc="center left", bbox_to_anchor=(1.02, 0.5))

    fig.savefig(output_path, dpi=180, bbox_inches="tight")
    print(f"Wrote plot to {output_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
