%% SPDX-FileCopyrightInfo: Copyright © DuMux Project contributors, see AUTHORS.md in root folder
%% SPDX-License-Identifier: CC-BY-4.0

flowchart TD
    A(Compact car) --> D(Sedan)
    D --> E(Pickup)
    E -->F(Hummer)
    B(Truck) --> E
    C(Tank) --> F
